name: Generate Documentation
description: Generate documentation of the project
inputs:
  default-runtime-version: 
    description: "Version used to setup runtime"
    required: true
    
runs:
  using: "composite"
  steps:  
    - name: Set up runtime
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.default-runtime-version }}
        extensions: mbstring, intl, json, curl
  
    - name: Install dependencies
      shell: bash
      run: composer run install:ci
  
    - name: Generate documentation (with docs generator)
      if: false
      shell: bash
      run: composer run docs
  
    - name: Generate documentation (with docs open-api-generator)
      if: false
      shell: bash
      run: echo TODO
      # uses: openapitools/openapi-generator-cli@v2
      # with:
      #   generator: php
      #   config-file: templates/php/config.yaml
      #   openapi-file: schema/openapispec-upsun-processed.json
