<?php

/**
 * Low level AddressMetadata (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class AddressMetadata implements JsonSerializable
{
    protected const DISCRIMINATOR = null;

    public function __construct(
        public readonly \Upsun\Model\AddressMetadataMetadata|null $metadata = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'metadata' => $this->metadata,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

