<?php

/**
 * Low level Alert (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class Alert implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'Alert';

    private static array $attributeMap = [
        'id' => 'id',
        'active' => 'active',
        'alerts_sent' => 'alerts_sent',
        'last_alert_at' => 'last_alert_at',
        'updated_at' => 'updated_at',
        'config' => 'config'
    ];

    public function __construct(
        public readonly ?string $id = null,
        public readonly ?bool $active = null,
        public readonly ?int $alerts_sent = null,
        public readonly ?\DateTime $last_alert_at = null,
        public readonly ?\DateTime $updated_at = null,
        public readonly ?object $config = null,
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'active' => $this->active,
            'alerts_sent' => $this->alerts_sent,
            'last_alert_at' => $this->last_alert_at,
            'updated_at' => $this->updated_at,
            'config' => $this->config,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

