<?php

/**
 * Low level AListOfFilesToAddToTheRepositoryDuringInitializationInner (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class AListOfFilesToAddToTheRepositoryDuringInitializationInner implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly string $path,
        public readonly int $mode,
        public readonly string $contents
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'path' => $this->path,
            'mode' => $this->mode,
            'contents' => $this->contents,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
    public static function openAPIFormats()
        {
            return self::$openAPIFormats;
        }
    
        /**
         * Array of nullable properties
         *
         * @return array
         */
        protected static function openAPINullables(): array
        {
            return self::$openAPINullables;
        }
        
            protected static array $openAPINullables = [
                'path' => false,
                'mode' => false,
                'contents' => false
            ];
        protected static $openAPIFormats = [
            'path' => null,
            'mode' => null,
            'contents' => null
        ];
}

