<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level AutoscalerCPUResources (auto-generated)
 *
 * CPU scaling settings
 *
 * @author
 * @license   MIT
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class AutoscalerCPUResources implements Model, JsonSerializable
{
    public function __construct(
        private readonly ?float $min = null,
        private readonly ?float $max = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'min' => $this->min,
            'max' => $this->max,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
    * Minimum CPUs when scaling down vertically
    */
    public function getMin(): ?float
    {
        return $this->min;
    }

    /**
    * Maximum CPUs when scaling up vertically
    */
    public function getMax(): ?float
    {
        return $this->max;
    }
}
