<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level AutoscalerScalingCooldown (auto-generated)
 * Scaling cooldown settings
 *
 * @license   MIT
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class AutoscalerScalingCooldown implements Model, JsonSerializable
{
    public function __construct(
        private readonly ?int $up = null,
        private readonly ?int $down = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'up' => $this->up,
            'down' => $this->down,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

   /**
    * Number of seconds to wait until scaling up can be done again (since last attempt)
    */
    public function getUp(): ?int
    {
        return $this->up;
    }

   /**
    * Number of seconds to wait until scaling down can be done again (since last attempt)
    */
    public function getDown(): ?int
    {
        return $this->down;
    }
}


