<?php

/**
 * Low level BitbucketServerIntegrationPatch (auto-generated)
 *
 * @author    Upsun Advocacy Team
 * @license   MIT
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */

namespace Upsun\Model;

use JsonSerializable;

final class BitbucketServerIntegrationPatch implements ModelInterface, JsonSerializable
{
    public function __construct(
        private readonly string $type,
        private readonly string $url,
        private readonly string $username,
        private readonly string $token,
        private readonly string $project,
        private readonly string $repository,
        private readonly ?bool $fetchBranches = null,
        private readonly ?bool $pruneBranches = null,
        private readonly ?string $environmentInitResources = null,
        private readonly ?bool $buildPullRequests = null,
        private readonly ?bool $pullRequestsCloneParentData = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'url' => $this->url,
            'username' => $this->username,
            'token' => $this->token,
            'project' => $this->project,
            'repository' => $this->repository,
            'fetchBranches' => $this->fetchBranches,
            'pruneBranches' => $this->pruneBranches,
            'environmentInitResources' => $this->environmentInitResources,
            'buildPullRequests' => $this->buildPullRequests,
            'pullRequestsCloneParentData' => $this->pullRequestsCloneParentData,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function getToken(): string
    {
        return $this->token;
    }

    public function getProject(): string
    {
        return $this->project;
    }

    public function getRepository(): string
    {
        return $this->repository;
    }

    public function getFetchBranches(): ?bool
    {
        return $this->fetchBranches;
    }

    public function getPruneBranches(): ?bool
    {
        return $this->pruneBranches;
    }

    public function getEnvironmentInitResources(): ?string
    {
        return $this->environmentInitResources;
    }

    public function getBuildPullRequests(): ?bool
    {
        return $this->buildPullRequests;
    }

    public function getPullRequestsCloneParentData(): ?bool
    {
        return $this->pullRequestsCloneParentData;
    }
}
