<?php

/**
 * Low level BitbucketIntegration (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class BitbucketIntegration implements JsonSerializable
{
    public const ENVIRONMENT_INIT_RESOURCES__DEFAULT = 'default';
    public const ENVIRONMENT_INIT_RESOURCES_MANUAL = 'manual';
    public const ENVIRONMENT_INIT_RESOURCES_MINIMUM = 'minimum';
    public const ENVIRONMENT_INIT_RESOURCES_PARENT = 'parent';

    public function __construct(
        private readonly string $type,
        private readonly bool $fetchBranches,
        private readonly bool $pruneBranches,
        private readonly string $environmentInitResources,
        private readonly string $repository,
        private readonly bool $buildPullRequests,
        private readonly bool $pullRequestsCloneParentData,
        private readonly bool $resyncPullRequests,
        private readonly ?\DateTime $createdAt = null,
        private readonly ?\DateTime $updatedAt = null,
        private readonly ?\Upsun\Model\TheOAuth2ConsumerInformationOptional $appCredentials = null,
        private readonly ?\Upsun\Model\TheAddonCredentialInformationOptional $addonCredentials = null,
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'createdAt' => $this->createdAt,
            'updatedAt' => $this->updatedAt,
            'type' => $this->type,
            'fetchBranches' => $this->fetchBranches,
            'pruneBranches' => $this->pruneBranches,
            'environmentInitResources' => $this->environmentInitResources,
            'repository' => $this->repository,
            'buildPullRequests' => $this->buildPullRequests,
            'pullRequestsCloneParentData' => $this->pullRequestsCloneParentData,
            'resyncPullRequests' => $this->resyncPullRequests,
            'appCredentials' => $this->appCredentials,
            'addonCredentials' => $this->addonCredentials,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @return \DateTime|null
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @return string
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * @return bool
     */
    public function getFetchBranches(): bool
    {
        return $this->fetchBranches;
    }

    /**
     * @return bool
     */
    public function getPruneBranches(): bool
    {
        return $this->pruneBranches;
    }

    /**
     * @return string
     */
    public function getEnvironmentInitResources(): string
    {
        return $this->environmentInitResources;
    }

    /**
     * @return string
     */
    public function getRepository(): string
    {
        return $this->repository;
    }

    /**
     * @return bool
     */
    public function getBuildPullRequests(): bool
    {
        return $this->buildPullRequests;
    }

    /**
     * @return bool
     */
    public function getPullRequestsCloneParentData(): bool
    {
        return $this->pullRequestsCloneParentData;
    }

    /**
     * @return bool
     */
    public function getResyncPullRequests(): bool
    {
        return $this->resyncPullRequests;
    }

    /**
     * @return \Upsun\Model\TheOAuth2ConsumerInformationOptional|null
     */
    public function getAppCredentials(): ?\Upsun\Model\TheOAuth2ConsumerInformationOptional
    {
        return $this->appCredentials;
    }

    /**
     * @return \Upsun\Model\TheAddonCredentialInformationOptional|null
     */
    public function getAddonCredentials(): ?\Upsun\Model\TheAddonCredentialInformationOptional
    {
        return $this->addonCredentials;
    }
}

