<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level Bitbucket (auto-generated)
 * Bitbucket integration configurations
 *
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class Bitbucket implements Model, JsonSerializable
{
    public function __construct(
        private readonly ?bool $enabled = null,
        private readonly ?string $role = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'enabled' => $this->enabled,
            'role' => $this->role,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * The integration is enabled.
     */
    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    /**
     * Minimum required role for creating the integration.
     */
    public function getRole(): ?string
    {
        return $this->role;
    }
}
