<?php

/**
 * Low level BlackfireIntegration (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class BlackfireIntegration implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'BlackfireIntegration';

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    private static array $openAPITypes = [
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'type' => 'string',
        'environments_credentials' => 'array<string,\Upsun\Model\BlackfireEnvironmentsCredentialsValue>',
        'continuous_profiling' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    private static array $openAPIFormats = [
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'type' => null,
        'environments_credentials' => null,
        'continuous_profiling' => null
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    private static array $attributeMap = [
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'type' => 'type',
        'environments_credentials' => 'environments_credentials',
        'continuous_profiling' => 'continuous_profiling'
    ];
    
    public function __construct(
        public readonly \DateTime $created_at = null,
        public readonly \DateTime $updated_at = null,
        public readonly string $type = null,
        public readonly ?array $environments_credentials = null,
        public readonly bool $continuous_profiling = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'type' => $this->type,
            'environments_credentials' => $this->environments_credentials,
            'continuous_profiling' => $this->continuous_profiling,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return true; // All properties in this model are nullable
    }
}

