<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level BlackfireProfilesRecommendations200Response (auto-generated)
 *
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class BlackfireProfilesRecommendations200Response implements Model, JsonSerializable
{
    public function __construct(
        private readonly string $projectId,
        private readonly string $environmentId,
        private readonly string $branchMachineName,
        private readonly string $agent,
        private readonly int $from,
        private readonly int $to,
        private readonly array $recommendations,
        private readonly int $total,
        private readonly ?string $transaction = null,
        private readonly ?array $testedTransactions = [],
        private readonly ?array $untestedTopTransactions = [],
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'projectId' => $this->projectId,
            'environmentId' => $this->environmentId,
            'branchMachineName' => $this->branchMachineName,
            'agent' => $this->agent,
            'from' => $this->from,
            'to' => $this->to,
            'recommendations' => $this->recommendations,
            'total' => $this->total,
            'transaction' => $this->transaction,
            'testedTransactions' => $this->testedTransactions,
            'untestedTopTransactions' => $this->untestedTopTransactions,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getProjectId(): string
    {
        return $this->projectId;
    }

    public function getEnvironmentId(): string
    {
        return $this->environmentId;
    }

    public function getBranchMachineName(): string
    {
        return $this->branchMachineName;
    }

    public function getAgent(): string
    {
        return $this->agent;
    }

    public function getFrom(): int
    {
        return $this->from;
    }

    public function getTo(): int
    {
        return $this->to;
    }

    /**
     * @return BlackfireProfilesRecommendations200ResponseRecommendationsInner[]
     */
    public function getRecommendations(): array
    {
        return $this->recommendations;
    }

    public function getTotal(): int
    {
        return $this->total;
    }

    public function getTransaction(): ?string
    {
        return $this->transaction;
    }

    public function getTestedTransactions(): ?array
    {
        return $this->testedTransactions;
    }

    public function getUntestedTopTransactions(): ?array
    {
        return $this->untestedTopTransactions;
    }
}
