<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level CertificatePatch (auto-generated)
 *
 * @license   Apache V2
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class CertificatePatch implements Model, JsonSerializable
{
    public function __construct(
        private readonly ?array $chain = [],
        private readonly ?bool $isInvalid = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'chain' => $this->chain,
            'isInvalid' => $this->isInvalid,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getChain(): ?array
    {
        return $this->chain;
    }

    /**
     * Whether this certificate should be skipped during provisioning
     */
    public function getIsInvalid(): ?bool
    {
        return $this->isInvalid;
    }
}
