<?php

/**
 * Low level CommandsToManageTheApplicationSLifecycle (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class CommandsToManageTheApplicationSLifecycle implements JsonSerializable
{

    private static array $attributeMap = [
        'preStart' => 'pre_start',
        'start' => 'start'
    ];

    public function __construct(
        private readonly ?string $preStart = null,
        private readonly ?string $start = null,
    ) {
    }

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return [
            'pre_start' => '?string',
            'start' => '?string',
        ];
    }

    public function jsonSerialize(): array
    {
        return [
            'preStart' => $this->preStart,
            'start' => $this->start,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * @return string|null
     */
    public function getPreStart(): ?string
    {
        return $this->preStart;
    }

    /**
     * @return string|null
     */
    public function getStart(): ?string
    {
        return $this->start;
    }
}

