<?php

/**
 * Low level ConfigurationRelatedToTheSourceCodeOfTheApplication (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class ConfigurationRelatedToTheSourceCodeOfTheApplication implements JsonSerializable
{
    protected const DISCRIMINATOR = null;

    public function __construct(
        public readonly string $root = null,
        public readonly ?array $operations = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'root' => $this->root,
            'operations' => $this->operations,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

