<?php

/**
 * Low level ConfigurationAboutTheTrafficRoutedToThisVersion (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class ConfigurationAboutTheTrafficRoutedToThisVersion implements JsonSerializable
{
    public function __construct(
        private readonly int $percentage,
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'percentage' => $this->percentage,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getPercentage(): int
    {
        return $this->percentage;
    }
}
