<?php

/**
 * Low level Connection (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class Connection implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'Connection';

    private static array $attributeMap = [
        'provider' => 'provider',
        'provider_type' => 'provider_type',
        'is_mandatory' => 'is_mandatory',
        'subject' => 'subject',
        'email_address' => 'email_address',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at'
    ];

    public function __construct(
        public readonly ?string $provider = null,
        public readonly ?string $provider_type = null,
        public readonly ?bool $is_mandatory = null,
        public readonly ?string $subject = null,
        public readonly ?string $email_address = null,
        public readonly ?\DateTime $created_at = null,
        public readonly ?\DateTime $updated_at = null,
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'provider' => $this->provider,
            'provider_type' => $this->provider_type,
            'is_mandatory' => $this->is_mandatory,
            'subject' => $this->subject,
            'email_address' => $this->email_address,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

