<?php

/**
 * Low level ContainerProfilesValueValue (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class ContainerProfilesValueValue implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'Container_profiles_value_value';

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    private static array $openAPITypes = [
        'cpu' => 'float',
        'memory' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    private static array $openAPIFormats = [
        'cpu' => 'float',
        'memory' => null
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    private static array $attributeMap = [
        'cpu' => 'cpu',
        'memory' => 'memory'
    ];
    
    public function __construct(
        public readonly float $cpu = null,
        public readonly int $memory = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'cpu' => $this->cpu,
            'memory' => $this->memory,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return true; // All properties in this model are nullable
    }
}

