<?php

/**
 * Low level CreateTicketRequest (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class CreateTicketRequest implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'create_ticket_request';

    private static array $attributeMap = [
        'subject' => 'subject',
        'description' => 'description',
        'requesterId' => 'requester_id',
        'priority' => 'priority',
        'subscriptionId' => 'subscription_id',
        'organizationId' => 'organization_id',
        'affectedUrl' => 'affected_url',
        'followupTid' => 'followup_tid',
        'category' => 'category',
        'attachments' => 'attachments',
        'collaboratorIds' => 'collaborator_ids'
    ];

    public function __construct(
        private string $subject,
        private string $description,
        private ?string $requesterId = null,
        private ?string $priority = null,
        private ?string $subscriptionId = null,
        private ?string $organizationId = null,
        private ?string $affectedUrl = null,
        private ?string $followupTid = null,
        private ?string $category = null,
        private ?array $attachments = [],
        private ?array $collaboratorIds = [],
    ) {
        if ($this->attachments) {
            $this->attachments = array_map(function ($item) {
                if ($item instanceof \Upsun\Model\CreateTicketRequestAttachmentsInner) {
                    return $item;
                }
                return \Upsun\ObjectSerializer::deserialize($item, \Upsun\Model\CreateTicketRequestAttachmentsInner::class);
            }, $this->attachments);
        }
    }

    public function jsonSerialize(): array
    {
        return [
            'subject' => $this->subject,
            'description' => $this->description,
            'requesterId' => $this->requesterId,
            'priority' => $this->priority,
            'subscriptionId' => $this->subscriptionId,
            'organizationId' => $this->organizationId,
            'affectedUrl' => $this->affectedUrl,
            'followupTid' => $this->followupTid,
            'category' => $this->category,
            'attachments' => $this->attachments,
            'collaboratorIds' => $this->collaboratorIds,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    //public function getSubject(): string
    public function getSubject(): string
    {
        return $this->subject;
    }
    //public function getDescription(): string
    public function getDescription(): string
    {
        return $this->description;
    }
    //public function getRequesterId(): ?string
    public function getRequesterId(): ?string
    {
        return $this->requesterId;
    }
    //public function getPriority(): ?string
    public function getPriority(): ?string
    {
        return $this->priority;
    }
    //public function getSubscriptionId(): ?string
    public function getSubscriptionId(): ?string
    {
        return $this->subscriptionId;
    }
    //public function getOrganizationId(): ?string
    public function getOrganizationId(): ?string
    {
        return $this->organizationId;
    }
    //public function getAffectedUrl(): ?string
    public function getAffectedUrl(): ?string
    {
        return $this->affectedUrl;
    }
    //public function getFollowupTid(): ?string
    public function getFollowupTid(): ?string
    {
        return $this->followupTid;
    }
    //public function getCategory(): ?string
    public function getCategory(): ?string
    {
        return $this->category;
    }
    //public function getAttachments(): ?[]
    public function getAttachments(): ?array
    {
        return $this->attachments;
    }
    //public function getCollaboratorIds(): ?[]
    public function getCollaboratorIds(): ?array
    {
        return $this->collaboratorIds;
    }
}

