<?php

/**
 * Low level CreateProjectInviteRequestEnvironmentsInner (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class CreateProjectInviteRequestEnvironmentsInner implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly string|null $id = null,
        public readonly string|null $role = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'role' => $this->role,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

