<?php

/**
 * Low level CreateProjectInviteRequestEnvironmentsInner (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class CreateProjectInviteRequestEnvironmentsInner implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'create_project_invite_request_environments_inner';

    private static array $attributeMap = [
        'id' => 'id',
        'role' => 'role'
    ];

    public function __construct(
        private ?string $id = null,
        private ?string $role = null,
    ) {
    }

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return [
            'id' => 'string',
            'role' => 'string',
        ];
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'role' => $this->role,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    //public function getId(): ?string
    public function getId(): ?string
    {
        return $this->id;
    }
    //public function getRole(): ?string
    public function getRole(): ?string
    {
        return $this->role;
    }
}

