<?php

/**
 * Low level DataRetentionConfigurationValue (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class DataRetentionConfigurationValue implements JsonSerializable
{

    private static array $attributeMap = [
        'maxBackups' => 'max_backups',
        'defaultConfig' => 'default_config'
    ];

    public function __construct(
        private readonly int $maxBackups,
        private readonly \Upsun\Model\DefaultConfig $defaultConfig,
    ) {
    }

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return [
            'max_backups' => 'int',
            'default_config' => '\Upsun\Model\DefaultConfig',
        ];
    }

    public function jsonSerialize(): array
    {
        return [
            'maxBackups' => $this->maxBackups,
            'defaultConfig' => $this->defaultConfig,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * @return int
     */
    public function getMaxBackups(): int
    {
        return $this->maxBackups;
    }
    /**
     * @return \Upsun\Model\DefaultConfig
     */
    public function getDefaultConfig(): \Upsun\Model\DefaultConfig
    {
        return $this->defaultConfig;
    }
}

