<?php

/**
 * Low level DomainPatch (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class DomainPatch implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly ?array $attributes = null,
        public readonly bool|null $is_default = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'attributes' => $this->attributes,
            'is_default' => $this->is_default,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

