<?php

/**
 * Low level EnvironmentSourceOperationInput (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class EnvironmentSourceOperationInput implements JsonSerializable
{
    public function __construct(
        private readonly string $operation,
        private readonly array $variables,
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'operation' => $this->operation,
            'variables' => $this->variables,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getOperation(): string
    {
        return $this->operation;
    }

    public function getVariables(): array
    {
        return $this->variables;
    }
}
