<?php

/**
 * Low level EnvironmentOperationInput (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class EnvironmentOperationInput implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'EnvironmentOperationInput';

    private static array $attributeMap = [
        'service' => 'service',
        'operation' => 'operation'
    ];
        /**
         * Array of attributes to setter functions (for deserialization of responses)
         */
        private static $setters = [
            'service' => 'setService',
            'operation' => 'setOperation'
        ];
    
        /**
         * Array of attributes to getter functions (for serialization of requests)
         */
        private static $getters = [
            'service' => 'getService',
            'operation' => 'getOperation'
        ];
    
    
    public function __construct(
        public readonly string $service,
        public readonly string $operation,
    ) {
    }

    private static array $openAPINullables = [
        'service' => false,
        'operation' => false
    ];

    public function jsonSerialize(): array
    {
        return [
            'service' => $this->service,
            'operation' => $this->operation,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
}

