<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level FastlyIntegrationCreateInput (auto-generated)
 *
 * @author    Upsun Advocacy Team
 * @license   MIT
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class FastlyIntegrationCreateInput implements Model, JsonSerializable
{
    public function __construct(
        private readonly string $type,
        private readonly string $token,
        private readonly string $serviceId,
        private readonly ?array $events = [],
        private readonly ?array $environments = [],
        private readonly ?array $excludedEnvironments = [],
        private readonly ?array $states = [],
        private readonly ?string $result = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'token' => $this->token,
            'serviceId' => $this->serviceId,
            'events' => $this->events,
            'environments' => $this->environments,
            'excludedEnvironments' => $this->excludedEnvironments,
            'states' => $this->states,
            'result' => $this->result,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getToken(): string
    {
        return $this->token;
    }

    public function getServiceId(): string
    {
        return $this->serviceId;
    }

    public function getEvents(): ?array
    {
        return $this->events;
    }

    public function getEnvironments(): ?array
    {
        return $this->environments;
    }

    public function getExcludedEnvironments(): ?array
    {
        return $this->excludedEnvironments;
    }

    public function getStates(): ?array
    {
        return $this->states;
    }

    public function getResult(): ?string
    {
        return $this->result;
    }
}
