<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level GetOrgPrepaymentInfo200Response (auto-generated)
 *
 * @author    Upsun Advocacy Team
 * @license   MIT
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class GetOrgPrepaymentInfo200Response implements Model, JsonSerializable
{
    public function __construct(
        private readonly ?PrepaymentObject $prepayment = null,
        private readonly ?GetOrgPrepaymentInfo200ResponseLinks $links = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'prepayment' => $this->prepayment,
            'links' => $this->links,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
    * Prepayment information for an organization.
    */
    public function getPrepayment(): ?PrepaymentObject
    {
        return $this->prepayment;
    }

    public function getLinks(): ?GetOrgPrepaymentInfo200ResponseLinks
    {
        return $this->links;
    }
}
