<?php

/**
 * Low level GetTypeAllowance200Response (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class GetTypeAllowance200Response implements JsonSerializable
{
    public readonly \Upsun\Model\GetTypeAllowance200ResponseCurrencies $currencies;

    public function __construct(
        \Upsun\Model\GetTypeAllowance200ResponseCurrencies $currencies = null,
    ) {
        $this->currencies = $currencies;
    }

    public function getCurrencies(): \Upsun\Model\GetTypeAllowance200ResponseCurrencies|null
    {
        return $this->currencies;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'currencies' => $this->currencies,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

