<?php

/**
 * Low level GitLabIntegrationPatch (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class GitLabIntegrationPatch implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'GitLabIntegrationPatch';

    private static array $attributeMap = [
        'type' => 'type',
        'fetch_branches' => 'fetch_branches',
        'prune_branches' => 'prune_branches',
        'environment_init_resources' => 'environment_init_resources',
        'token' => 'token',
        'base_url' => 'base_url',
        'project' => 'project',
        'build_merge_requests' => 'build_merge_requests',
        'build_wip_merge_requests' => 'build_wip_merge_requests',
        'merge_requests_clone_parent_data' => 'merge_requests_clone_parent_data'
    ];

    public function __construct(
        public readonly ?string $type = null,
        public readonly ?bool $fetch_branches = null,
        public readonly ?bool $prune_branches = null,
        public readonly ?string $environment_init_resources = null,
        public readonly ?string $token = null,
        public readonly ?string $base_url = null,
        public readonly ?string $project = null,
        public readonly ?bool $build_merge_requests = null,
        public readonly ?bool $build_wip_merge_requests = null,
        public readonly ?bool $merge_requests_clone_parent_data = null,
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'fetch_branches' => $this->fetch_branches,
            'prune_branches' => $this->prune_branches,
            'environment_init_resources' => $this->environment_init_resources,
            'token' => $this->token,
            'base_url' => $this->base_url,
            'project' => $this->project,
            'build_merge_requests' => $this->build_merge_requests,
            'build_wip_merge_requests' => $this->build_wip_merge_requests,
            'merge_requests_clone_parent_data' => $this->merge_requests_clone_parent_data,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

