<?php

/**
 * Low level GoogleSSOConfig (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated by OpenAPI Generator
 * Do NOT edit this class manually.
 */

namespace Upsun\Model;

use JsonSerializable;

final class GoogleSSOConfig implements ModelInterface, JsonSerializable
{
    public function __construct(
        private readonly ?string $providerType = null,
        private readonly ?string $domain = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'providerType' => $this->providerType,
            'domain' => $this->domain,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
    * SSO provider type.
    */
    public function getProviderType(): ?string
    {
        return $this->providerType;
    }

    /**
    * Google hosted domain.
    */
    public function getDomain(): ?string
    {
        return $this->domain;
    }
}
