<?php

/**
 * Low level HalLinks (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class HalLinks implements JsonSerializable
{

    private static array $attributeMap = [
        'self' => 'self',
        'previous' => 'previous',
        'next' => 'next'
    ];

    public function __construct(
        private ?\Upsun\Model\HalLinksSelf $self = null,
        private ?\Upsun\Model\HalLinksPrevious $previous = null,
        private ?\Upsun\Model\HalLinksNext $next = null,
    ) {
    }

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return [
            'self' => '\Upsun\Model\HalLinksSelf',
            'previous' => '\Upsun\Model\HalLinksPrevious',
            'next' => '\Upsun\Model\HalLinksNext',
        ];
    }

    public function jsonSerialize(): array
    {
        return [
            'self' => $this->self,
            'previous' => $this->previous,
            'next' => $this->next,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * @return \Upsun\Model\HalLinksSelf|null
     */
    public function getSelf(): ?\Upsun\Model\HalLinksSelf
    {
        return $this->self;
    }
    /**
     * @return \Upsun\Model\HalLinksPrevious|null
     */
    public function getPrevious(): ?\Upsun\Model\HalLinksPrevious
    {
        return $this->previous;
    }
    /**
     * @return \Upsun\Model\HalLinksNext|null
     */
    public function getNext(): ?\Upsun\Model\HalLinksNext
    {
        return $this->next;
    }
}

