<?php

/**
 * Low level HealthPagerDutyNotificationIntegrationConfigurations (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class HealthPagerDutyNotificationIntegrationConfigurations implements JsonSerializable
{

    public function __construct(
        private readonly ?bool $enabled = null,
        private readonly ?string $role = null,
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'enabled' => $this->enabled,
            'role' => $this->role,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * @return bool|null
     */
    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    /**
     * @return string|null
     */
    public function getRole(): ?string
    {
        return $this->role;
    }
}

