<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level Hooks1 (auto-generated)
 * Scripts executed at various points in the lifecycle of the task
 *
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class Hooks1 implements Model, JsonSerializable
{


    public function __construct(
        private readonly ?string $build,
        private readonly ?string $deploy,
    ) {
    }


    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'build' => $this->build,
            'deploy' => $this->deploy,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

   /**
    * Hook executed after the build process
    */
    public function getBuild(): ?string
    {
        return $this->build;
    }

   /**
    * Hook executed before the task's run command
    */
    public function getDeploy(): ?string
    {
        return $this->deploy;
    }
}

