<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level HttpMetricsTimelineUrls200ResponseFilters (auto-generated)
 *
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class HttpMetricsTimelineUrls200ResponseFilters implements Model, JsonSerializable
{


    public function __construct(
        private readonly int $maxApplicableFilters,
        private readonly ?array $fields = [],
    ) {
    }


    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'maxApplicableFilters' => $this->maxApplicableFilters,
            'fields' => $this->fields,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getMaxApplicableFilters(): int
    {
        return $this->maxApplicableFilters;
    }

   /**
    * @return HttpMetricsTimelineUrls200ResponseFiltersFieldsValue[]|null
    */
    public function getFields(): ?array
    {
        return $this->fields;
    }
}

