<?php

/**
 * Low level HttpAccessPermissions1 (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated by OpenAPI Generator
 * Do NOT edit this class manually.
 */

namespace Upsun\Model;

use JsonSerializable;

final class HttpAccessPermissions1 implements ModelInterface, JsonSerializable
{
    public function __construct(
        private readonly ?bool $isEnabled = null,
        private readonly ?array $addresses = [],
        private readonly ?array $basicAuth = [],
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'isEnabled' => $this->isEnabled,
            'addresses' => $this->addresses,
            'basicAuth' => $this->basicAuth,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getIsEnabled(): ?bool
    {
        return $this->isEnabled;
    }
    /**
     * @return AddressGrantsInner[]|null
     */

    public function getAddresses(): ?array
    {
        return $this->addresses;
    }

    public function getBasicAuth(): ?array
    {
        return $this->basicAuth;
    }
}
