<?php

/**
 * Low level ImagesValueValue (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class ImagesValueValue implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'Images_value_value';

    private static array $attributeMap = [
        'available' => 'available'
    ];
        /**
         * Array of attributes to setter functions (for deserialization of responses)
         */
        private static $setters = [
            'available' => 'setAvailable'
        ];
    
        /**
         * Array of attributes to getter functions (for serialization of requests)
         */
        private static $getters = [
            'available' => 'getAvailable'
        ];
    
        /**
         * Array of attributes to setter functions (for deserialization of responses)
         */
        private static $setters = [
            'available' => 'setAvailable'
        ];
    
        /**
         * Array of attributes to getter functions (for serialization of requests)
         */
        private static $getters = [
            'available' => 'getAvailable'
        ];
    
    public function __construct(
        public readonly bool $available
    ) {
    }

    private static array $openAPINullables = [
        'available' => false
    ];

    public function jsonSerialize(): array
    {
        return [
            'available' => $this->available,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
}

