<?php

namespace Upsun\Model;

use JsonSerializable;
use Upsun\Model\DeploymentTargetPatch;

/**
 * Low level KubernetesDeploymentTargetStoragePatch (auto-generated)
 *
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class KubernetesDeploymentTargetStoragePatch implements Model, JsonSerializable, DeploymentTargetPatch
{

    public const TYPE_DEDICATED = 'dedicated';
    public const TYPE_ENTERPRISE = 'enterprise';
    public const TYPE_FOUNDATION = 'foundation';
    public const TYPE_KUBERNETES = 'kubernetes';

    public function __construct(
        private readonly string $type,
        private readonly string $name,
    ) {
    }


    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'name' => $this->name,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

   /**
    * The type of the deployment target
    */
    public function getType(): string
    {
        return $this->type;
    }

   /**
    * The name of the deployment target
    */
    public function getName(): string
    {
        return $this->name;
    }
}

