<?php

/**
 * Low level ListOrgMembers200Response (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class ListOrgMembers200Response implements JsonSerializable
{
    public readonly int|null $count;
    /**
     * @var \Upsun\Model\OrganizationMember[]|null
     */
    public readonly ?array $items;
    public readonly \Upsun\Model\ListLinks|null $_links;

    public function __construct(
        int|null $count = null,
        ?array $items = null,
        \Upsun\Model\ListLinks|null $_links = null
    ) {
        $this->count = $count;
        $this->items = $items;
        $this->_links = $_links;
    }

    public function getCount(): int|null
    {
        return $this->count;
    }
    /**
     * @return \Upsun\Model\OrganizationMember[]|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }
    public function getLinks(): \Upsun\Model\ListLinks|null
    {
        return $this->_links;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'count' => $this->count,
            'items' => $this->items,
            '_links' => $this->_links,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

