<?php

/**
 * Low level ListPlans200Response (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class ListPlans200Response implements JsonSerializable
{
    public readonly int $count;
    public readonly \Upsun\Model\Plan[] $plans;
    public readonly \Upsun\Model\HalLinks $_links;

    public function __construct(
        int $count = null,
        \Upsun\Model\Plan[] $plans = null,
        \Upsun\Model\HalLinks $_links = null,
    ) {
        $this->count = $count;
        $this->plans = $plans;
        $this->_links = $_links;
    }

    public function getCount(): int|null
    {
        return $this->count;
    }
    public function getPlans(): \Upsun\Model\Plan[]|null
    {
        return $this->plans;
    }
    public function getLinks(): \Upsun\Model\HalLinks|null
    {
        return $this->_links;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'count' => $this->count,
            'plans' => $this->plans,
            '_links' => $this->_links,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

