<?php

/**
 * Low level ListUserExtendedAccess200Response (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class ListUserExtendedAccess200Response implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        /**
         * @var array
         */
        public readonly array $items,
        public readonly \Upsun\Model\ListLinks $_links
    ) {
    }

    private static array $openAPINullables = [
        'items' => false,
        '_links' => false
    ];

    public function jsonSerialize(): array
    {
        return [
            'items' => $this->items,
            '_links' => $this->_links,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
}

