<?php

/**
 * Low level NewRelicIntegrationPatch (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class NewRelicIntegrationPatch implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly string $type,
        /**
         * @var string[]
         */
        public readonly array $extra,
        public readonly string $url,
        public readonly string $license_key,
        public readonly bool $tls_verify
    ) {
    }

    private static array $openAPINullables = [
        'type' => false,
        'extra' => false,
        'url' => false,
        'license_key' => false,
        'tls_verify' => false
    ];

    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'extra' => $this->extra,
            'url' => $this->url,
            'license_key' => $this->license_key,
            'tls_verify' => $this->tls_verify,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
}

