<?php

/**
 * Low level Order (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class Order implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly string $id,
        public readonly string $status,
        public readonly string $owner,
        public readonly \Upsun\Model\Address $address,
        public readonly string $company,
        public readonly string $vat_number,
        public readonly \DateTime $billing_period_start,
        public readonly \DateTime $billing_period_end,
        public readonly \Upsun\Model\OrderBillingPeriodLabel $billing_period_label,
        public readonly int $billing_period_duration,
        public readonly ?\DateTime $paid_on,
        public readonly int $total,
        public readonly int $total_formatted,
        public readonly \Upsun\Model\Components $components,
        public readonly string $currency,
        public readonly string $invoice_url,
        public readonly \DateTime $last_refreshed,
        public readonly bool $invoiced,
        /**
         * @var array
         */
        public readonly array $line_items,
        public readonly \Upsun\Model\OrderLinks $_links
    ) {
    }

    private static array $openAPINullables = [
        'id' => false,
        'status' => false,
        'owner' => false,
        'address' => false,
        'company' => false,
        'vat_number' => false,
        'billing_period_start' => false,
        'billing_period_end' => false,
        'billing_period_label' => false,
        'billing_period_duration' => false,
        'paid_on' => true,
        'total' => false,
        'total_formatted' => false,
        'components' => false,
        'currency' => false,
        'invoice_url' => false,
        'last_refreshed' => false,
        'invoiced' => false,
        'line_items' => false,
        '_links' => false
    ];

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'status' => $this->status,
            'owner' => $this->owner,
            'address' => $this->address,
            'company' => $this->company,
            'vat_number' => $this->vat_number,
            'billing_period_start' => $this->billing_period_start,
            'billing_period_end' => $this->billing_period_end,
            'billing_period_label' => $this->billing_period_label,
            'billing_period_duration' => $this->billing_period_duration,
            'paid_on' => $this->paid_on,
            'total' => $this->total,
            'total_formatted' => $this->total_formatted,
            'components' => $this->components,
            'currency' => $this->currency,
            'invoice_url' => $this->invoice_url,
            'last_refreshed' => $this->last_refreshed,
            'invoiced' => $this->invoiced,
            'line_items' => $this->line_items,
            '_links' => $this->_links,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
}

