<?php

/**
 * Low level OrganizationEstimationObjectSubscriptionsListInner (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class OrganizationEstimationObjectSubscriptionsListInner implements JsonSerializable
{
    public readonly string $license_id;
    public readonly string $project_title;
    public readonly string $total;
    public readonly \Upsun\Model\OrganizationEstimationObjectSubscriptionsListInnerUsage $usage;

    public function __construct(
        string $license_id = null,
        string $project_title = null,
        string $total = null,
        \Upsun\Model\OrganizationEstimationObjectSubscriptionsListInnerUsage $usage = null,
    ) {
        $this->license_id = $license_id;
        $this->project_title = $project_title;
        $this->total = $total;
        $this->usage = $usage;
    }

    public function getLicenseId(): string|null
    {
        return $this->license_id;
    }
    public function getProjectTitle(): string|null
    {
        return $this->project_title;
    }
    public function getTotal(): string|null
    {
        return $this->total;
    }
    public function getUsage(): \Upsun\Model\OrganizationEstimationObjectSubscriptionsListInnerUsage|null
    {
        return $this->usage;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'license_id' => $this->license_id,
            'project_title' => $this->project_title,
            'total' => $this->total,
            'usage' => $this->usage,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

