<?php

/**
 * Low level OrganizationInvitation (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class OrganizationInvitation implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly string $id,
        public readonly string $state,
        public readonly string $organization_id,
        public readonly string $email,
        public readonly \Upsun\Model\OrganizationInvitationOwner $owner,
        public readonly \DateTime $created_at,
        public readonly \DateTime $updated_at,
        public readonly ?\DateTime $finished_at,
        /**
         * @var array
         */
        public readonly array $permissions
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'state' => $this->state,
            'organization_id' => $this->organization_id,
            'email' => $this->email,
            'owner' => $this->owner,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'finished_at' => $this->finished_at,
            'permissions' => $this->permissions,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
    public static function openAPIFormats()
        {
            return self::$openAPIFormats;
        }
    
        /**
         * Array of nullable properties
         *
         * @return array
         */
        protected static function openAPINullables(): array
        {
            return self::$openAPINullables;
        }
        
            protected static array $openAPINullables = [
                'id' => false,
                'state' => false,
                'organization_id' => false,
                'email' => false,
                'owner' => false,
                'created_at' => false,
                'updated_at' => false,
                'finished_at' => true,
                'permissions' => false
            ];
        protected static $openAPIFormats = [
            'id' => 'uuid',
            'state' => null,
            'organization_id' => null,
            'email' => 'email',
            'owner' => null,
            'created_at' => 'date-time',
            'updated_at' => 'date-time',
            'finished_at' => 'date-time',
            'permissions' => null
        ];
}

