<?php

/**
 * Low level OrganizationEstimationObjectSubscriptions (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class OrganizationEstimationObjectSubscriptions implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly string $total,
        /**
         * @var array
         */
        public readonly array $list
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'total' => $this->total,
            'list' => $this->list,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
    public static function openAPIFormats()
        {
            return self::$openAPIFormats;
        }
    
        /**
         * Array of nullable properties
         *
         * @return array
         */
        protected static function openAPINullables(): array
        {
            return self::$openAPINullables;
        }
        
            protected static array $openAPINullables = [
                'total' => false,
                'list' => false
            ];
        protected static $openAPIFormats = [
            'total' => null,
            'list' => null
        ];
}

