<?php

/**
 * Low level Organization (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class Organization implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'Organization';

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    private static array $openAPITypes = [
        'id' => 'string',
        'type' => 'string',
        'owner_id' => 'string',
        'namespace' => 'string',
        'name' => 'string',
        'label' => 'string',
        'country' => 'string',
        'capabilities' => 'string[]',
        'vendor' => 'string',
        'status' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        '_links' => '\Upsun\Model\OrganizationLinks'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    private static array $openAPIFormats = [
        'id' => 'ulid',
        'type' => null,
        'owner_id' => 'uuid',
        'namespace' => null,
        'name' => null,
        'label' => null,
        'country' => null,
        'capabilities' => null,
        'vendor' => null,
        'status' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        '_links' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    private static array $attributeMap = [
        'id' => 'id',
        'type' => 'type',
        'owner_id' => 'owner_id',
        'namespace' => 'namespace',
        'name' => 'name',
        'label' => 'label',
        'country' => 'country',
        'capabilities' => 'capabilities',
        'vendor' => 'vendor',
        'status' => 'status',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        '_links' => '_links'
    ];
    
    public function __construct(
        public readonly string|null $id = null,
        public readonly string|null $type = null,
        public readonly string|null $owner_id = null,
        public readonly string|null $namespace = null,
        public readonly string|null $name = null,
        public readonly string|null $label = null,
        public readonly string|null $country = null,
        public readonly ?array $capabilities = null,
        public readonly string|null $vendor = null,
        public readonly string|null $status = null,
        public readonly \DateTime|null $created_at = null,
        public readonly \DateTime|null $updated_at = null,
        public readonly \Upsun\Model\OrganizationLinks|null $_links = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'type' => $this->type,
            'owner_id' => $this->owner_id,
            'namespace' => $this->namespace,
            'name' => $this->name,
            'label' => $this->label,
            'country' => $this->country,
            'capabilities' => $this->capabilities,
            'vendor' => $this->vendor,
            'status' => $this->status,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            '_links' => $this->_links,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return true; // All properties in this model are nullable
    }
}

