<?php

/**
 * Low level OrganizationAlertConfig (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class OrganizationAlertConfig implements JsonSerializable
{
    public readonly string $id;
    public readonly bool $active;
    public readonly float $alerts_sent;
    public readonly string $last_alert_at;
    public readonly string $updated_at;
    public readonly \Upsun\Model\OrganizationAlertConfigConfig $config;

    public function __construct(
        string $id = null,
        bool $active = null,
        float $alerts_sent = null,
        string $last_alert_at = null,
        string $updated_at = null,
        \Upsun\Model\OrganizationAlertConfigConfig $config = null,
    ) {
        $this->id = $id;
        $this->active = $active;
        $this->alerts_sent = $alerts_sent;
        $this->last_alert_at = $last_alert_at;
        $this->updated_at = $updated_at;
        $this->config = $config;
    }

    public function getId(): string|null
    {
        return $this->id;
    }
    public function getActive(): bool|null
    {
        return $this->active;
    }
    public function getAlertsSent(): float|null
    {
        return $this->alerts_sent;
    }
    public function getLastAlertAt(): string|null
    {
        return $this->last_alert_at;
    }
    public function getUpdatedAt(): string|null
    {
        return $this->updated_at;
    }
    public function getConfig(): \Upsun\Model\OrganizationAlertConfigConfig|null
    {
        return $this->config;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'id' => $this->id,
            'active' => $this->active,
            'alerts_sent' => $this->alerts_sent,
            'last_alert_at' => $this->last_alert_at,
            'updated_at' => $this->updated_at,
            'config' => $this->config,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

