<?php

/**
 * Low level OrganizationAlertConfigConfigThreshold (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class OrganizationAlertConfigConfigThreshold implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'OrganizationAlertConfig_config_threshold';

    private static array $attributeMap = [
        'formatted' => 'formatted',
        'amount' => 'amount',
        'currencyCode' => 'currency_code',
        'currencySymbol' => 'currency_symbol'
    ];

    public function __construct(
        private ?string $formatted = null,
        private ?float $amount = null,
        private ?string $currencyCode = null,
        private ?string $currencySymbol = null,
    ) {
    }

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return [
            'formatted' => 'string',
            'amount' => 'float',
            'currency_code' => 'string',
            'currency_symbol' => 'string',
        ];
    }

    public function jsonSerialize(): array
    {
        return [
            'formatted' => $this->formatted,
            'amount' => $this->amount,
            'currencyCode' => $this->currencyCode,
            'currencySymbol' => $this->currencySymbol,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * Formatted threshold value.
     *
     * @return string|null
     */
    public function getFormatted(): ?string
    {
        return $this->formatted;
    }
    /**
     * Threshold value.
     *
     * @return float|null
     */
    public function getAmount(): ?float
    {
        return $this->amount;
    }
    /**
     * Threshold currency code.
     *
     * @return string|null
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }
    /**
     * Threshold currency symbol.
     *
     * @return string|null
     */
    public function getCurrencySymbol(): ?string
    {
        return $this->currencySymbol;
    }
}

