<?php

/**
 * Low level PagerDutyIntegrationCreateInput (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class PagerDutyIntegrationCreateInput implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'PagerDutyIntegrationCreateInput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    private static array $openAPITypes = [
        'type' => 'string',
        'routing_key' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    private static array $openAPIFormats = [
        'type' => null,
        'routing_key' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    private static array $attributeMap = [
        'type' => 'type',
        'routing_key' => 'routing_key'
    ];
    
    public function __construct(
        public readonly string $type = null,
        public readonly string $routing_key = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'routing_key' => $this->routing_key,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return true; // All properties in this model are nullable
    }
}

