<?php

/**
 * Low level ProfileCurrentTrialProjects (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class ProfileCurrentTrialProjects implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'Profile_current_trial_projects';

    private static array $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'total' => 'total'
    ];

    public function __construct(
        private ?string $id = null,
        private ?string $name = null,
        private ?\Upsun\Model\ProfileCurrentTrialProjectsTotal $total = null,
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'total' => $this->total,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    //public function getId(): ?string
    public function getId(): ?string
    {
        return $this->id;
    }
    //public function getName(): ?string
    public function getName(): ?string
    {
        return $this->name;
    }
    //public function getTotal(): ?\Upsun\Model\ProfileCurrentTrialProjectsTotal
    public function getTotal(): ?\Upsun\Model\ProfileCurrentTrialProjectsTotal
    {
        return $this->total;
    }
}

