<?php

/**
 * Low level Profile (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class Profile implements JsonSerializable
{
    public readonly string $id;
    public readonly string $display_name;
    public readonly string $email;
    public readonly string $username;
    public readonly string $type;
    public readonly string $picture;
    public readonly string $company_type;
    public readonly string $company_name;
    public readonly string $currency;
    public readonly string $vat_number;
    public readonly string $company_role;
    public readonly string $website_url;
    public readonly bool $new_ui;
    public readonly string $ui_colorscheme;
    public readonly string $default_catalog;
    public readonly string $project_options_url;
    public readonly bool $marketing;
    public readonly \DateTime $created_at;
    public readonly \DateTime $updated_at;
    public readonly string $billing_contact;
    public readonly string $security_contact;
    public readonly \Upsun\Model\ProfileCurrentTrial $current_trial;
    public readonly bool $invoiced;

    public function __construct(
        string $id = null,
        string $display_name = null,
        string $email = null,
        string $username = null,
        string $type = null,
        string $picture = null,
        string $company_type = null,
        string $company_name = null,
        string $currency = null,
        string $vat_number = null,
        string $company_role = null,
        string $website_url = null,
        bool $new_ui = null,
        string $ui_colorscheme = null,
        string $default_catalog = null,
        string $project_options_url = null,
        bool $marketing = null,
        \DateTime $created_at = null,
        \DateTime $updated_at = null,
        string $billing_contact = null,
        string $security_contact = null,
        \Upsun\Model\ProfileCurrentTrial $current_trial = null,
        bool $invoiced = null,
    ) {
        $this->id = $id;
        $this->display_name = $display_name;
        $this->email = $email;
        $this->username = $username;
        $this->type = $type;
        $this->picture = $picture;
        $this->company_type = $company_type;
        $this->company_name = $company_name;
        $this->currency = $currency;
        $this->vat_number = $vat_number;
        $this->company_role = $company_role;
        $this->website_url = $website_url;
        $this->new_ui = $new_ui;
        $this->ui_colorscheme = $ui_colorscheme;
        $this->default_catalog = $default_catalog;
        $this->project_options_url = $project_options_url;
        $this->marketing = $marketing;
        $this->created_at = $created_at;
        $this->updated_at = $updated_at;
        $this->billing_contact = $billing_contact;
        $this->security_contact = $security_contact;
        $this->current_trial = $current_trial;
        $this->invoiced = $invoiced;
    }

    public function getId(): string|null
    {
        return $this->id;
    }
    public function getDisplayName(): string|null
    {
        return $this->display_name;
    }
    public function getEmail(): string|null
    {
        return $this->email;
    }
    public function getUsername(): string|null
    {
        return $this->username;
    }
    public function getType(): string|null
    {
        return $this->type;
    }
    public function getPicture(): string|null
    {
        return $this->picture;
    }
    public function getCompanyType(): string|null
    {
        return $this->company_type;
    }
    public function getCompanyName(): string|null
    {
        return $this->company_name;
    }
    public function getCurrency(): string|null
    {
        return $this->currency;
    }
    public function getVatNumber(): string|null
    {
        return $this->vat_number;
    }
    public function getCompanyRole(): string|null
    {
        return $this->company_role;
    }
    public function getWebsiteUrl(): string|null
    {
        return $this->website_url;
    }
    public function getNewUi(): bool|null
    {
        return $this->new_ui;
    }
    public function getUiColorscheme(): string|null
    {
        return $this->ui_colorscheme;
    }
    public function getDefaultCatalog(): string|null
    {
        return $this->default_catalog;
    }
    public function getProjectOptionsUrl(): string|null
    {
        return $this->project_options_url;
    }
    public function getMarketing(): bool|null
    {
        return $this->marketing;
    }
    public function getCreatedAt(): \DateTime|null
    {
        return $this->created_at;
    }
    public function getUpdatedAt(): \DateTime|null
    {
        return $this->updated_at;
    }
    public function getBillingContact(): string|null
    {
        return $this->billing_contact;
    }
    public function getSecurityContact(): string|null
    {
        return $this->security_contact;
    }
    public function getCurrentTrial(): \Upsun\Model\ProfileCurrentTrial|null
    {
        return $this->current_trial;
    }
    public function getInvoiced(): bool|null
    {
        return $this->invoiced;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'id' => $this->id,
            'display_name' => $this->display_name,
            'email' => $this->email,
            'username' => $this->username,
            'type' => $this->type,
            'picture' => $this->picture,
            'company_type' => $this->company_type,
            'company_name' => $this->company_name,
            'currency' => $this->currency,
            'vat_number' => $this->vat_number,
            'company_role' => $this->company_role,
            'website_url' => $this->website_url,
            'new_ui' => $this->new_ui,
            'ui_colorscheme' => $this->ui_colorscheme,
            'default_catalog' => $this->default_catalog,
            'project_options_url' => $this->project_options_url,
            'marketing' => $this->marketing,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'billing_contact' => $this->billing_contact,
            'security_contact' => $this->security_contact,
            'current_trial' => $this->current_trial,
            'invoiced' => $this->invoiced,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

