<?php

/**
 * Low level ProjectInvitation (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class ProjectInvitation implements JsonSerializable
{
    public readonly string $id;
    public readonly string $state;
    public readonly string $project_id;
    public readonly string $role;
    public readonly string $email;
    public readonly \Upsun\Model\OrganizationInvitationOwner $owner;
    public readonly \DateTime $created_at;
    public readonly \DateTime $updated_at;
    public readonly \DateTime $finished_at;
    public readonly \Upsun\Model\ProjectInvitationEnvironmentsInner[] $environments;

    public function __construct(
        string $id = null,
        string $state = null,
        string $project_id = null,
        string $role = null,
        string $email = null,
        \Upsun\Model\OrganizationInvitationOwner $owner = null,
        \DateTime $created_at = null,
        \DateTime $updated_at = null,
        \DateTime $finished_at = null,
        \Upsun\Model\ProjectInvitationEnvironmentsInner[] $environments = null,
    ) {
        $this->id = $id;
        $this->state = $state;
        $this->project_id = $project_id;
        $this->role = $role;
        $this->email = $email;
        $this->owner = $owner;
        $this->created_at = $created_at;
        $this->updated_at = $updated_at;
        $this->finished_at = $finished_at;
        $this->environments = $environments;
    }

    public function getId(): string|null
    {
        return $this->id;
    }
    public function getState(): string|null
    {
        return $this->state;
    }
    public function getProjectId(): string|null
    {
        return $this->project_id;
    }
    public function getRole(): string|null
    {
        return $this->role;
    }
    public function getEmail(): string|null
    {
        return $this->email;
    }
    public function getOwner(): \Upsun\Model\OrganizationInvitationOwner|null
    {
        return $this->owner;
    }
    public function getCreatedAt(): \DateTime|null
    {
        return $this->created_at;
    }
    public function getUpdatedAt(): \DateTime|null
    {
        return $this->updated_at;
    }
    public function getFinishedAt(): \DateTime|null
    {
        return $this->finished_at;
    }
    public function getEnvironments(): \Upsun\Model\ProjectInvitationEnvironmentsInner[]|null
    {
        return $this->environments;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'id' => $this->id,
            'state' => $this->state,
            'project_id' => $this->project_id,
            'role' => $this->role,
            'email' => $this->email,
            'owner' => $this->owner,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'finished_at' => $this->finished_at,
            'environments' => $this->environments,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

