<?php

/**
 * Low level ProjectCarbon (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated by OpenAPI Generator
 * Do NOT edit this class manually.
 */

namespace Upsun\Model;

use JsonSerializable;

final class ProjectCarbon implements ModelInterface, JsonSerializable
{
    public function __construct(
        private readonly ?string $projectId = null,
        private readonly ?string $projectTitle = null,
        private readonly ?MetricsMetadata $meta = null,
        private readonly ?array $values = [],
        private readonly ?float $total = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'projectId' => $this->projectId,
            'projectTitle' => $this->projectTitle,
            'meta' => $this->meta,
            'values' => $this->values,
            'total' => $this->total,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
    * The ID of the project.
    */
    public function getProjectId(): ?string
    {
        return $this->projectId;
    }

    /**
    * The title of the project.
    */
    public function getProjectTitle(): ?string
    {
        return $this->projectTitle;
    }

    public function getMeta(): ?MetricsMetadata
    {
        return $this->meta;
    }
    /**
     * @return MetricsValue[]|null
     */

    public function getValues(): ?array
    {
        return $this->values;
    }

    /**
    * The calculated total of the metric for the given interval.
    */
    public function getTotal(): ?float
    {
        return $this->total;
    }
}
