<?php

namespace Upsun\Model;

use JsonSerializable;

/**
 * Low level ProjectAddon (auto-generated)
 * Project add-on. Uses discriminator on `type` to select field shape.
 *
 * @license   MIT
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class ProjectAddon implements Model, JsonSerializable
{

    public const STATUS_REQUESTED = 'requested';
    public const STATUS_ACTIVE = 'active';
    public const STATUS_FAILED = 'failed';

    public function __construct(
        private readonly string $id,
        private readonly string $type,
        private readonly string $sku,
        private readonly int $quantity,
        private readonly ?string $unit = null,
        private readonly ?array $allowedValues = [],
        private readonly ?array $activities = [],
        private readonly ?string $projectId = null,
        private readonly ?string $status = null,
        private readonly ?string $title = null,
        private readonly ?\DateTime $createdAt = null,
        private readonly ?\DateTime $updatedAt = null,
        private readonly ?ProjectAddonBaseLinks $links = null,
    ) {
    }


    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'type' => $this->type,
            'sku' => $this->sku,
            'quantity' => $this->quantity,
            'projectId' => $this->projectId,
            'status' => $this->status,
            'title' => $this->title,
            'unit' => $this->unit,
            'allowedValues' => $this->allowedValues,
            'createdAt' => $this->createdAt?->format(DATE_ATOM),
            'updatedAt' => $this->updatedAt?->format(DATE_ATOM),
            'activities' => $this->activities,
            'links' => $this->links,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

   /**
    * The ID of the add-on.
    */
    public function getId(): string
    {
        return $this->id;
    }

   /**
    * The type of the add-on.
    */
    public function getType(): string
    {
        return $this->type;
    }

   /**
    * The SKU of the add-on.
    */
    public function getSku(): string
    {
        return $this->sku;
    }

   /**
    * The quantity of the add-on.
    */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

   /**
    * The ID of the project.
    */
    public function getProjectId(): ?string
    {
        return $this->projectId;
    }

   /**
    * Lifecycle status of the add-on.
    */
    public function getStatus(): ?string
    {
        return $this->status;
    }

   /**
    * Human-friendly title of the add-on or SKU.
    */
    public function getTitle(): ?string
    {
        return $this->title;
    }

   /**
    * Unit for quantity-based add-ons when applicable.
    */
    public function getUnit(): ?string
    {
        return $this->unit;
    }

   /**
    * Allowed values for the add-on depending on user role and options.
    * @return ProjectAddonBaseAllowedValuesInner[]|null
    */
    public function getAllowedValues(): ?array
    {
        return $this->allowedValues;
    }

   /**
    * The date and time when the resource was created.
    */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

   /**
    * The date and time when the resource was last updated.
    */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

   /**
    * Activities related to the add-on.
    * @return Activity[]|null
    */
    public function getActivities(): ?array
    {
        return $this->activities;
    }

    public function getLinks(): ?ProjectAddonBaseLinks
    {
        return $this->links;
    }
}

