<?php

/**
 * Low level ProjectInfo (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class ProjectInfo implements JsonSerializable
{
    public readonly string $title;
    public readonly string $name;
    public readonly string $namespace;
    public readonly string $organization;
    public readonly object $capabilities;
    public readonly object $settings;

    public function __construct(
        string $title,
        string $name,
        string $namespace,
        string $organization,
        object $capabilities,
        object $settings,
    ) {
        $this->title = $title;
        $this->name = $name;
        $this->namespace = $namespace;
        $this->organization = $organization;
        $this->capabilities = $capabilities;
        $this->settings = $settings;
    }

    public function getTitle(): string
    {
        return $this->title;
    }
    public function getName(): string
    {
        return $this->name;
    }
    public function getNamespace(): string
    {
        return $this->namespace;
    }
    public function getOrganization(): string
    {
        return $this->organization;
    }
    public function getCapabilities(): object
    {
        return $this->capabilities;
    }
    public function getSettings(): object
    {
        return $this->settings;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'title' => $this->title,
            'name' => $this->name,
            'namespace' => $this->namespace,
            'organization' => $this->organization,
            'capabilities' => $this->capabilities,
            'settings' => $this->settings,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

