<?php

/**
 * Low level ResourcesForDevelopmentEnvironments (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class ResourcesForDevelopmentEnvironments implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly bool $legacy_development = null,
        public readonly float $max_cpu = null,
        public readonly int $max_memory = null,
        public readonly int $max_environments = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'legacy_development' => $this->legacy_development,
            'max_cpu' => $this->max_cpu,
            'max_memory' => $this->max_memory,
            'max_environments' => $this->max_environments,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

