<?php

/**
 * Low level SplunkIntegration (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class SplunkIntegration implements JsonSerializable
{
    public function __construct(
        private readonly string $type,
        private readonly array $extra,
        private readonly string $url,
        private readonly string $index,
        private readonly string $sourcetype,
        private readonly bool $tlsVerify,
        private readonly ?string $createdAt = null,
        private readonly ?string $updatedAt = null,
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'createdAt' => $this->createdAt,
            'updatedAt' => $this->updatedAt,
            'type' => $this->type,
            'extra' => $this->extra,
            'url' => $this->url,
            'index' => $this->index,
            'sourcetype' => $this->sourcetype,
            'tlsVerify' => $this->tlsVerify,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getCreatedAt(): ?string
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?string
    {
        return $this->updatedAt;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getExtra(): array
    {
        return $this->extra;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function getIndex(): string
    {
        return $this->index;
    }

    public function getSourcetype(): string
    {
        return $this->sourcetype;
    }

    public function getTlsVerify(): bool
    {
        return $this->tlsVerify;
    }
}
