<?php

/**
 * Low level SplunkIntegrationPatch (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class SplunkIntegrationPatch implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly string $type,
        /**
         * @var string[]
         */
        public readonly array $extra,
        public readonly string $url,
        public readonly string $index,
        public readonly string $token,
        public readonly string $sourcetype,
        public readonly bool $tls_verify
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'type' => $this->type,
            'extra' => $this->extra,
            'url' => $this->url,
            'index' => $this->index,
            'token' => $this->token,
            'sourcetype' => $this->sourcetype,
            'tls_verify' => $this->tls_verify,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
    public static function openAPIFormats()
        {
            return self::$openAPIFormats;
        }
    
        /**
         * Array of nullable properties
         *
         * @return array
         */
        protected static function openAPINullables(): array
        {
            return self::$openAPINullables;
        }
        
            protected static array $openAPINullables = [
                'type' => false,
                'extra' => false,
                'url' => false,
                'index' => false,
                'token' => false,
                'sourcetype' => false,
                'tls_verify' => false
            ];
        protected static $openAPIFormats = [
            'type' => null,
            'extra' => null,
            'url' => null,
            'index' => null,
            'token' => null,
            'sourcetype' => null,
            'tls_verify' => null
        ];
}

