<?php

/**
 * Low level SSHKey (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class SSHKey implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly int|null $key_id = null,
        public readonly int|null $uid = null,
        public readonly string|null $fingerprint = null,
        public readonly string|null $title = null,
        public readonly string|null $value = null,
        public readonly string|null $changed = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'key_id' => $this->key_id,
            'uid' => $this->uid,
            'fingerprint' => $this->fingerprint,
            'title' => $this->title,
            'value' => $this->value,
            'changed' => $this->changed,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

