<?php

/**
 * Low level StringFilter (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class StringFilter implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'StringFilter';

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    private static array $openAPITypes = [
        'eq' => 'string',
        'ne' => 'string',
        'in' => 'string',
        'nin' => 'string',
        'between' => 'string',
        'contains' => 'string',
        'starts' => 'string',
        'ends' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    private static array $openAPIFormats = [
        'eq' => null,
        'ne' => null,
        'in' => null,
        'nin' => null,
        'between' => null,
        'contains' => null,
        'starts' => null,
        'ends' => null
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    private static array $attributeMap = [
        'eq' => 'eq',
        'ne' => 'ne',
        'in' => 'in',
        'nin' => 'nin',
        'between' => 'between',
        'contains' => 'contains',
        'starts' => 'starts',
        'ends' => 'ends'
    ];
    
    public function __construct(
        public readonly string|null $eq = null,
        public readonly string|null $ne = null,
        public readonly string|null $in = null,
        public readonly string|null $nin = null,
        public readonly string|null $between = null,
        public readonly string|null $contains = null,
        public readonly string|null $starts = null,
        public readonly string|null $ends = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'eq' => $this->eq,
            'ne' => $this->ne,
            'in' => $this->in,
            'nin' => $this->nin,
            'between' => $this->between,
            'contains' => $this->contains,
            'starts' => $this->starts,
            'ends' => $this->ends,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return true; // All properties in this model are nullable
    }
}

