<?php

/**
 * Low level SubscriptionAddonsObject (auto-generated)
 *
 * The list of available and current addons for the license.
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class SubscriptionAddonsObject implements ModelInterface, JsonSerializable
{
    public function __construct(
        private readonly ?SubscriptionAddonsObjectAvailable $available = null,
        private readonly ?SubscriptionAddonsObjectCurrent $current = null,
        private readonly ?SubscriptionAddonsObjectUpgradesAvailable $upgradesAvailable = null,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'available' => $this->available,
            'current' => $this->current,
            'upgradesAvailable' => $this->upgradesAvailable,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
    * The list of available addons.
    */
    public function getAvailable(): ?SubscriptionAddonsObjectAvailable
    {
        return $this->available;
    }

    /**
    * The list of existing addons and their current values.
    */
    public function getCurrent(): ?SubscriptionAddonsObjectCurrent
    {
        return $this->current;
    }

    /**
    * The upgrades available for current addons.
    */
    public function getUpgradesAvailable(): ?SubscriptionAddonsObjectUpgradesAvailable
    {
        return $this->upgradesAvailable;
    }
}
