<?php

/**
 * Low level SubscriptionAddonsObject (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class SubscriptionAddonsObject implements JsonSerializable
{
    public const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'SubscriptionAddonsObject';

    private static array $attributeMap = [
        'available' => 'available',
        'current' => 'current',
        'upgradesAvailable' => 'upgrades_available'
    ];

    public function __construct(
        private ?\Upsun\Model\SubscriptionAddonsObjectAvailable $available = null,
        private ?\Upsun\Model\SubscriptionAddonsObjectCurrent $current = null,
        private ?\Upsun\Model\SubscriptionAddonsObjectUpgradesAvailable $upgradesAvailable = null,
    ) {
    }

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return [
            'available' => '\Upsun\Model\SubscriptionAddonsObjectAvailable',
            'current' => '\Upsun\Model\SubscriptionAddonsObjectCurrent',
            'upgrades_available' => '\Upsun\Model\SubscriptionAddonsObjectUpgradesAvailable',
        ];
    }

    public function jsonSerialize(): array
    {
        return [
            'available' => $this->available,
            'current' => $this->current,
            'upgradesAvailable' => $this->upgradesAvailable,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    //public function getAvailable(): ?\Upsun\Model\SubscriptionAddonsObjectAvailable
    public function getAvailable(): ?\Upsun\Model\SubscriptionAddonsObjectAvailable
    {
        return $this->available;
    }
    //public function getCurrent(): ?\Upsun\Model\SubscriptionAddonsObjectCurrent
    public function getCurrent(): ?\Upsun\Model\SubscriptionAddonsObjectCurrent
    {
        return $this->current;
    }
    //public function getUpgradesAvailable(): ?\Upsun\Model\SubscriptionAddonsObjectUpgradesAvailable
    public function getUpgradesAvailable(): ?\Upsun\Model\SubscriptionAddonsObjectUpgradesAvailable
    {
        return $this->upgradesAvailable;
    }
}

