<?php

/**
 * Low level SubscriptionAddonsObjectCurrent (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class SubscriptionAddonsObjectCurrent implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly ?array $continuous_profiling = null,
        public readonly ?array $project_support_level = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'continuous_profiling' => $this->continuous_profiling,
            'project_support_level' => $this->project_support_level,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

