<?php

/**
 * Low level TheCronsDeploymentState (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class TheCronsDeploymentState implements JsonSerializable
{
    public const STATUS_PAUSED = 'paused';
    public const STATUS_RUNNING = 'running';
    public const STATUS_SLEEPING = 'sleeping';

    private static array $attributeMap = [
        'enabled' => 'enabled',
        'status' => 'status'
    ];

    public function __construct(
        private readonly bool $enabled,
        private readonly string $status,
    ) {
    }

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization (ObjectSerializer)
     */
    public static function openAPITypes(): array
    {
        return [
            'enabled' => 'bool',
            'status' => 'string',
        ];
    }

    public function jsonSerialize(): array
    {
        return [
            'enabled' => $this->enabled,
            'status' => $this->status,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * @return bool
     */
    public function getEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }
}

