<?php

/**
 * Low level TheCommitDistanceInfoBetweenParentAndChildEnvironments (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated by OpenAPI Generator
 * Do NOT edit this class manually.
 */

namespace Upsun\Model;

use JsonSerializable;

final class TheCommitDistanceInfoBetweenParentAndChildEnvironments implements ModelInterface, JsonSerializable
{
    public function __construct(
        private readonly ?int $commitsAhead,
        private readonly ?int $commitsBehind,
        private readonly ?string $parentRef,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'commitsAhead' => $this->commitsAhead,
            'commitsBehind' => $this->commitsBehind,
            'parentRef' => $this->parentRef,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getCommitsAhead(): ?int
    {
        return $this->commitsAhead;
    }

    public function getCommitsBehind(): ?int
    {
        return $this->commitsBehind;
    }

    public function getParentRef(): ?string
    {
        return $this->parentRef;
    }
}
