<?php

/**
 * Low level TheDisksResources (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use Upsun\ObjectSerializer;
use JsonSerializable;

final class TheDisksResources implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    public function __construct(
        public readonly ?int $temporary,
        public readonly ?int $instance,
        public readonly ?int $storage
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'temporary' => $this->temporary,
            'instance' => $this->instance,
            'storage' => $this->storage,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }   
    
}

