<?php

/**
 * Low level TheInformationAboutTheCommitter (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated by OpenAPI Generator
 * Do NOT edit this class manually.
 */

namespace Upsun\Model;

use JsonSerializable;

final class TheInformationAboutTheCommitter implements ModelInterface, JsonSerializable
{
    public function __construct(
        private readonly \DateTime $date,
        private readonly string $name,
        private readonly string $email,
    ) {
    }

    public function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'date' => $this->date?->format(DATE_ATOM),
            'name' => $this->name,
            'email' => $this->email,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getDate(): \DateTime
    {
        return $this->date;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getEmail(): string
    {
        return $this->email;
    }
}
