<?php

/**
 * Low level TheMinimumResourcesForThisService (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class TheMinimumResourcesForThisService implements JsonSerializable
{
    public function __construct(
        private readonly number $cpu,
        private readonly int $memory,
        private readonly ?int $disk = null,
        private readonly ?string $profileSize = null,
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'cpu' => $this->cpu,
            'memory' => $this->memory,
            'disk' => $this->disk,
            'profileSize' => $this->profileSize,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getCpu(): number
    {
        return $this->cpu;
    }

    public function getMemory(): int
    {
        return $this->memory;
    }

    public function getDisk(): ?int
    {
        return $this->disk;
    }

    public function getProfileSize(): ?string
    {
        return $this->profileSize;
    }
}
