<?php

/**
 * Low level TheRelationshipsOfTheApplicationToDefinedServicesValue (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class TheRelationshipsOfTheApplicationToDefinedServicesValue implements JsonSerializable
{
    public readonly string $service;
    public readonly string $endpoint;

    public function __construct(
        string $service = null,
        string $endpoint = null
    ) {
        $this->service = $service;
        $this->endpoint = $endpoint;
    }

    public function getService(): string
    {
        return $this->service;
    }
    public function getEndpoint(): string
    {
        return $this->endpoint;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'service' => $this->service,
            'endpoint' => $this->endpoint,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }
}

