<?php

/**
 * Low level UpdateUserRequest (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class UpdateUserRequest implements JsonSerializable
{
    public function __construct(
        private readonly ?string $username = null,
        private readonly ?string $firstName = null,
        private readonly ?string $lastName = null,
        private readonly ?string $picture = null,
        private readonly ?string $company = null,
        private readonly ?string $website = null,
        private readonly ?string $country = null,
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'username' => $this->username,
            'firstName' => $this->firstName,
            'lastName' => $this->lastName,
            'picture' => $this->picture,
            'company' => $this->company,
            'website' => $this->website,
            'country' => $this->country,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }
}
