<?php

/**
 * Low level UpdateOrgMemberRequest (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use ArrayAccess;
use JsonSerializable;

final class UpdateOrgMemberRequest implements JsonSerializable
{
    public const PERMISSIONS_ADMIN = 'admin';
    public const PERMISSIONS_BILLING = 'billing';
    public const PERMISSIONS_MEMBERS = 'members';
    public const PERMISSIONS_PLANS = 'plans';
    public const PERMISSIONS_PROJECTS_CREATE = 'projects:create';
    public const PERMISSIONS_PROJECTS_LIST = 'projects:list';

    public function __construct(
        private readonly ?array $permissions = [],
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'permissions' => $this->permissions,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * The organization member permissions.
     *
     * @return string[]|null
     */
    public function getPermissions(): ?array
    {
        return $this->permissions;
    }
}

