<?php

/**
 * Low level UserProjectAccess (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class UserProjectAccess implements JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     */
    private static string $openAPIModelName = 'UserProjectAccess';

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    private static array $openAPITypes = [
        'user_id' => 'string',
        'organization_id' => 'string',
        'project_id' => 'string',
        'project_title' => 'string',
        'permissions' => 'string[]',
        'granted_at' => '\DateTime',
        'updated_at' => '\DateTime',
        '_links' => '\Upsun\Model\TeamProjectAccessLinks'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    private static array $openAPIFormats = [
        'user_id' => 'uuid',
        'organization_id' => 'ulid',
        'project_id' => null,
        'project_title' => null,
        'permissions' => null,
        'granted_at' => 'date-time',
        'updated_at' => 'date-time',
        '_links' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    private static array $attributeMap = [
        'user_id' => 'user_id',
        'organization_id' => 'organization_id',
        'project_id' => 'project_id',
        'project_title' => 'project_title',
        'permissions' => 'permissions',
        'granted_at' => 'granted_at',
        'updated_at' => 'updated_at',
        '_links' => '_links'
    ];
    
    public function __construct(
        public readonly string|null $user_id = null,
        public readonly string|null $organization_id = null,
        public readonly string|null $project_id = null,
        public readonly string|null $project_title = null,
        public readonly ?array $permissions = null,
        public readonly \DateTime|null $granted_at = null,
        public readonly \DateTime|null $updated_at = null,
        public readonly \Upsun\Model\TeamProjectAccessLinks|null $_links = null
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'user_id' => $this->user_id,
            'organization_id' => $this->organization_id,
            'project_id' => $this->project_id,
            'project_title' => $this->project_title,
            'permissions' => $this->permissions,
            'granted_at' => $this->granted_at,
            'updated_at' => $this->updated_at,
            '_links' => $this->_links,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return true; // All properties in this model are nullable
    }
}

