<?php

/**
 * Low level Version (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */

namespace Upsun\Model;

use JsonSerializable;

final class Version implements JsonSerializable
{
    public function __construct(
        private readonly bool $locked,
        private readonly ConfigurationAboutTheTrafficRoutedToThisVersion $routing,
        private readonly ?string $commit = null,
    ) {
    }

    public static function getModelName(): string
    {
        return self::class;
    }

    public function jsonSerialize(): array
    {
        return [
            'commit' => $this->commit,
            'locked' => $this->locked,
            'routing' => $this->routing,
        ];
    }

    public function __toString(): string
    {
        return json_encode($this->jsonSerialize(), JSON_PRETTY_PRINT);
    }

    public function getCommit(): ?string
    {
        return $this->commit;
    }

    public function getLocked(): bool
    {
        return $this->locked;
    }

    public function getRouting(): ConfigurationAboutTheTrafficRoutedToThisVersion
    {
        return $this->routing;
    }
}
