<?php

namespace Upsun\Api;

use Exception;
use GuzzleHttp\Psr7\MultipartStream;
use InvalidArgumentException;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Upsun\Api\Serializer\ObjectSerializer;
use Upsun\Core\OAuthProvider;
use Upsun\Model\ApiToken;
use Upsun\Model\CreateApiTokenRequest;

/**
 * Low level ApiTokensApi (auto-generated)
 *
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually.
 */
final class ApiTokensApi extends AbstractApi
{
    private readonly ApiHeaderSelector $headerSelector;

    private ApiConfiguration $config;

    public function __construct(
        OAuthProvider $oauthProvider,
        ?ClientInterface $httpClient = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?ApiConfiguration $config = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?ApiHeaderSelector $selector = null,
    ) {
        parent::__construct(
            $oauthProvider,
            $httpClient,
            $requestFactory,
            AbstractApi::BASE_PATH,
            $streamFactory
        );

        $this->config = $config ?? (new ApiConfiguration())->setHost(AbstractApi::BASE_PATH);

        $this->headerSelector = $selector ?? new ApiHeaderSelector();
    }

    /**
     * Create an API token
     *
     * Creates an API token
     *
     * @param  string $userId
     *         The ID of the user. (required)
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws ClientExceptionInterface
     * @see https://docs.upsun.com/api/#tag/Api-Tokens/operation/create-api-token
     */
    public function createApiToken(
        string $userId,
        ?CreateApiTokenRequest $createApiTokenRequest = null
    ): ApiToken {
        return $this->createApiTokenWithHttpInfo(
            $userId,
            $createApiTokenRequest
        );
    }

    /**
     * Create an API token with HTTP Info
     *
     * @param  string $userId
     *         The ID of the user. (required)
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws ClientExceptionInterface
    */
    private function createApiTokenWithHttpInfo(
        string $userId,
        ?CreateApiTokenRequest $createApiTokenRequest = null
    ): ApiToken {
        $request = $this->createApiTokenRequest(
            $userId,
            $createApiTokenRequest
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\ApiToken',
                $request,
                $response
            );
        } catch (Exception $exception) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $exception->getCode(),
                    '/users/{user_id}/api-tokens'
                ),
                $request,
                $response ?? null,
                $exception
            );
        }
    }

    /**
     * Create request for operation 'createApiToken'
     *
     * @param  string $userId
     *         The ID of the user. (required)
     *
     * @throws InvalidArgumentException
     */
    private function createApiTokenRequest(
        string $userId,
        ?CreateApiTokenRequest $createApiTokenRequest = null
    ): RequestInterface {
        // verify the required parameter 'userId' is set
        if (empty($userId)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $userId
                when calling createApiToken'
            );
        }

        $resourcePath = '/users/{user_id}/api-tokens';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params

        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($createApiTokenRequest)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(
                    ObjectSerializer::sanitizeForSerialization($createApiTokenRequest)
                );
            } else {
                $httpBody = $createApiTokenRequest;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getUpsunClientHeader()) {
            $defaultHeaders['X-Upsun-Client'] = $this->config->getUpsunClientHeader();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Delete an API token
     *
     * Deletes an API token
     *
     * @param  string $userId
     *         The ID of the user. (required)
     * @param  string $tokenId (required)
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws ClientExceptionInterface
     * @see https://docs.upsun.com/api/#tag/Api-Tokens/operation/delete-api-token
     */
    public function deleteApiToken(
        string $userId,
        string $tokenId
    ): void {
        $this->deleteApiTokenWithHttpInfo(
            $userId,
            $tokenId
        );
    }

    /**
     * Delete an API token with HTTP Info
     *
     * @param  string $userId
     *         The ID of the user. (required)
     * @param  string $tokenId (required)
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws ClientExceptionInterface
    */
    private function deleteApiTokenWithHttpInfo(
        string $userId,
        string $tokenId
    ): void {
        $request = $this->deleteApiTokenRequest(
            $userId,
            $tokenId
        );

        try {
            $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );
        } catch (Exception $exception) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $exception->getCode(),
                    '/users/{user_id}/api-tokens/{token_id}'
                ),
                $request,
                $response ?? null,
                $exception
            );
        }
    }

    /**
     * Create request for operation 'deleteApiToken'
     *
     * @param  string $userId
     *         The ID of the user. (required)
     * @param  string $tokenId (required)
     *
     * @throws InvalidArgumentException
     */
    private function deleteApiTokenRequest(
        string $userId,
        string $tokenId
    ): RequestInterface {
        // verify the required parameter 'userId' is set
        if (empty($userId)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $userId
                when calling deleteApiToken'
            );
        }
        // verify the required parameter 'tokenId' is set
        if (empty($tokenId)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $tokenId
                when calling deleteApiToken'
            );
        }

        $resourcePath = '/users/{user_id}/api-tokens/{token_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params

        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }
        // path params

        if ($tokenId !== null) {
            $resourcePath = str_replace(
                '{' . 'token_id' . '}',
                ObjectSerializer::toPathValue($tokenId),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getUpsunClientHeader()) {
            $defaultHeaders['X-Upsun-Client'] = $this->config->getUpsunClientHeader();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('DELETE', $uri, $headers, $httpBody);
    }

    /**
     * Get an API token
     *
     * Retrieves the specified API token.
     *
     * @param  string $userId
     *         The ID of the user. (required)
     * @param  string $tokenId (required)
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws ClientExceptionInterface
     * @see https://docs.upsun.com/api/#tag/Api-Tokens/operation/get-api-token
     */
    public function getApiToken(
        string $userId,
        string $tokenId
    ): ApiToken {
        return $this->getApiTokenWithHttpInfo(
            $userId,
            $tokenId
        );
    }

    /**
     * Get an API token with HTTP Info
     *
     * @param  string $userId
     *         The ID of the user. (required)
     * @param  string $tokenId (required)
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws ClientExceptionInterface
    */
    private function getApiTokenWithHttpInfo(
        string $userId,
        string $tokenId
    ): ApiToken {
        $request = $this->getApiTokenRequest(
            $userId,
            $tokenId
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\ApiToken',
                $request,
                $response
            );
        } catch (Exception $exception) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $exception->getCode(),
                    '/users/{user_id}/api-tokens/{token_id}'
                ),
                $request,
                $response ?? null,
                $exception
            );
        }
    }

    /**
     * Create request for operation 'getApiToken'
     *
     * @param  string $userId
     *         The ID of the user. (required)
     * @param  string $tokenId (required)
     *
     * @throws InvalidArgumentException
     */
    private function getApiTokenRequest(
        string $userId,
        string $tokenId
    ): RequestInterface {
        // verify the required parameter 'userId' is set
        if (empty($userId)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $userId
                when calling getApiToken'
            );
        }
        // verify the required parameter 'tokenId' is set
        if (empty($tokenId)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $tokenId
                when calling getApiToken'
            );
        }

        $resourcePath = '/users/{user_id}/api-tokens/{token_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params

        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }
        // path params

        if ($tokenId !== null) {
            $resourcePath = str_replace(
                '{' . 'token_id' . '}',
                ObjectSerializer::toPathValue($tokenId),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getUpsunClientHeader()) {
            $defaultHeaders['X-Upsun-Client'] = $this->config->getUpsunClientHeader();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * List a user's API tokens
     *
     * Retrieves a list of API tokens associated with a single user.
     *
     * @param  string $userId
     *         The ID of the user. (required)
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws ClientExceptionInterface
     *
     * @return \Upsun\Model\ApiToken[]
     * @see https://docs.upsun.com/api/#tag/Api-Tokens/operation/list-api-tokens
     */
    public function listApiTokens(
        string $userId
    ): array {
        return $this->listApiTokensWithHttpInfo(
            $userId
        );
    }

    /**
     * List a user's API tokens with HTTP Info
     *
     * @param  string $userId
     *         The ID of the user. (required)
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws ClientExceptionInterface
     *
     * @return \Upsun\Model\ApiToken[]
    */
    private function listApiTokensWithHttpInfo(
        string $userId
    ): array {
        $request = $this->listApiTokensRequest(
            $userId
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\ApiToken[]',
                $request,
                $response
            );
        } catch (Exception $exception) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $exception->getCode(),
                    '/users/{user_id}/api-tokens'
                ),
                $request,
                $response ?? null,
                $exception
            );
        }
    }

    /**
     * Create request for operation 'listApiTokens'
     *
     * @param  string $userId
     *         The ID of the user. (required)
     *
     * @throws InvalidArgumentException
     */
    private function listApiTokensRequest(
        string $userId
    ): RequestInterface {
        // verify the required parameter 'userId' is set
        if (empty($userId)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $userId
                when calling listApiTokens'
            );
        }

        $resourcePath = '/users/{user_id}/api-tokens';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params

        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getUpsunClientHeader()) {
            $defaultHeaders['X-Upsun-Client'] = $this->config->getUpsunClientHeader();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }
}
