<?php

namespace Upsun\Api;

use Exception;
use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Promise\Promise;
use Upsun\ApiException;
use Upsun\Configuration;
use Upsun\DebugPlugin;
use Upsun\HeaderSelector;
use Upsun\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use InvalidArgumentException;
use Upsun\Core\OAuthProvider;

use function sprintf;

/**
 * Low level DeploymentApi (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */
final class DeploymentApi extends AbstractApi
{
    private readonly PluginClient $httpClient;

    private readonly PluginClient $httpAsyncClient;

    private readonly UriFactoryInterface $uriFactory;

    private readonly Configuration $config;

    private readonly HeaderSelector $headerSelector;

    private readonly int $hostIndex;

    private readonly RequestFactoryInterface $requestFactory;

    private readonly StreamFactoryInterface $streamFactory;

    public function __construct(
        OAuthProvider $oauthProvider,
        ?ClientInterface $httpClient = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        parent::__construct($oauthProvider, $httpClient, $requestFactory, 'https://api.platform.sh');

        $this->config = $config ?? (new Configuration())->setHost('https://api.platform.sh');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Get a single environment deployment
     *
     * @throws ApiException on non-2xx response
     * @throws InvalidArgumentException|Exception
     */
    public function getProjectsEnvironmentsDeployments(
        string $projectId,
        string $environmentId,
        string $deploymentId
    ): \Upsun\Model\Deployment {
        list($response) = $this->getProjectsEnvironmentsDeploymentsWithHttpInfo(
            $projectId,
            $environmentId,
            $deploymentId
        );
        return $response;
    }

    /**
     * Get a single environment deployment
     *
     * @throws InvalidArgumentException|Exception
     */
    public function getProjectsEnvironmentsDeploymentsWithHttpInfo(
        string $projectId,
        string $environmentId,
        string $deploymentId
    ): array {
        $request = $this->getProjectsEnvironmentsDeploymentsRequest(
            $projectId,
            $environmentId,
            $deploymentId
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\Deployment',
                $request,
                $response
            );

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Get a single environment deployment
     *
     * @throws InvalidArgumentException|Exception
     */
    public function getProjectsEnvironmentsDeploymentsAsync(
        string $projectId,
        string $environmentId,
        string $deploymentId
    ): Promise {
        return $this->getProjectsEnvironmentsDeploymentsAsyncWithHttpInfo(
            $projectId,
            $environmentId,
            $deploymentId
        )
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Get a single environment deployment
     *
     * @throws InvalidArgumentException|Exception
     */
    public function getProjectsEnvironmentsDeploymentsAsyncWithHttpInfo(
        string $projectId,
        string $environmentId,
        string $deploymentId
    ): Promise {
        $returnType = '\Upsun\Model\Deployment';
        $request = $this->getProjectsEnvironmentsDeploymentsRequest(
            $projectId,
            $environmentId,
            $deploymentId
        );

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProjectsEnvironmentsDeployments'
     *
     * @throws InvalidArgumentException
     */
    public function getProjectsEnvironmentsDeploymentsRequest(
        string $projectId,
        string $environmentId,
        string $deploymentId
    ): RequestInterface {
        // verify the required parameter 'projectId' is set
        if ($projectId === null || (is_array($projectId) && count($projectId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId when calling getProjectsEnvironmentsDeployments'
            );
        }
        // verify the required parameter 'environmentId' is set
        if ($environmentId === null || (is_array($environmentId) && count($environmentId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $environmentId when calling getProjectsEnvironmentsDeployments'
            );
        }
        // verify the required parameter 'deploymentId' is set
        if ($deploymentId === null || (is_array($deploymentId) && count($deploymentId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $deploymentId when calling getProjectsEnvironmentsDeployments'
            );
        }

        $resourcePath = '/projects/{projectId}/environments/{environmentId}/deployments/{deploymentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }
        // path params
        if ($environmentId !== null) {
            $resourcePath = str_replace(
                '{' . 'environmentId' . '}',
                ObjectSerializer::toPathValue($environmentId),
                $resourcePath
            );
        }
        // path params
        if ($deploymentId !== null) {
            $resourcePath = str_replace(
                '{' . 'deploymentId' . '}',
                ObjectSerializer::toPathValue($deploymentId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Get an environment&#39;s deployment information
     *
     * @throws ApiException on non-2xx response
     * @throws InvalidArgumentException|Exception
     */
    public function listProjectsEnvironmentsDeployments(
        string $projectId,
        string $environmentId
    ): array {
        list($response) = $this->listProjectsEnvironmentsDeploymentsWithHttpInfo(
            $projectId,
            $environmentId
        );
        return $response;
    }

    /**
     * Get an environment&#39;s deployment information
     *
     * @throws InvalidArgumentException|Exception
     */
    public function listProjectsEnvironmentsDeploymentsWithHttpInfo(
        string $projectId,
        string $environmentId
    ): array {
        $request = $this->listProjectsEnvironmentsDeploymentsRequest(
            $projectId,
            $environmentId
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\DeploymentCollection',
                $request,
                $response
            );

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Get an environment&#39;s deployment information
     *
     * @throws InvalidArgumentException|Exception
     */
    public function listProjectsEnvironmentsDeploymentsAsync(
        string $projectId,
        string $environmentId
    ): Promise {
        return $this->listProjectsEnvironmentsDeploymentsAsyncWithHttpInfo(
            $projectId,
            $environmentId
        )
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Get an environment&#39;s deployment information
     *
     * @throws InvalidArgumentException|Exception
     */
    public function listProjectsEnvironmentsDeploymentsAsyncWithHttpInfo(
        string $projectId,
        string $environmentId
    ): Promise {
        $returnType = '\Upsun\Model\Deployment[]';
        $request = $this->listProjectsEnvironmentsDeploymentsRequest(
            $projectId,
            $environmentId
        );

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'listProjectsEnvironmentsDeployments'
     *
     * @throws InvalidArgumentException
     */
    public function listProjectsEnvironmentsDeploymentsRequest(
        string $projectId,
        string $environmentId
    ): RequestInterface {
        // verify the required parameter 'projectId' is set
        if ($projectId === null || (is_array($projectId) && count($projectId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId when calling listProjectsEnvironmentsDeployments'
            );
        }
        // verify the required parameter 'environmentId' is set
        if ($environmentId === null || (is_array($environmentId) && count($environmentId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $environmentId when calling listProjectsEnvironmentsDeployments'
            );
        }

        $resourcePath = '/projects/{projectId}/environments/{environmentId}/deployments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }
        // path params
        if ($environmentId !== null) {
            $resourcePath = str_replace(
                '{' . 'environmentId' . '}',
                ObjectSerializer::toPathValue($environmentId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }


    /**
     * Create request
     */
    protected function createRequest(
        string $method,
        string|UriInterface $uri,
        array $headers = [],
        string|StreamInterface|null $body = null
    ): RequestInterface {
        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body) {
            if (is_string($body)) {
                if (!$this->streamFactory) {
                    throw new \RuntimeException(
                        'A stream factory is required to create a request with a string body.'
                    );
                }
                $body = $this->streamFactory->createStream($body);
            }
            $request = $request->withBody($body);
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $request,
                        $response
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0] . '00');
        $right = (int) ($rangeCode[0] . '99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
