<?php

namespace Upsun\Api;

use Upsun\Model\EnvironmentType;
use Exception;
use GuzzleHttp\Psr7\MultipartStream;
use Upsun\ApiException;
use Upsun\Configuration;
use Upsun\HeaderSelector;
use Upsun\ObjectSerializer;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use InvalidArgumentException;
use Upsun\Core\OAuthProvider;

/**
 * Low level EnvironmentTypeApi (auto-generated)
 *
 * @author    Upsun SDK Team
 * @license   Apache-2.0
 * @see       https://docs.upsun.com
 * @internal  This file was generated by OpenAPI Generator. Do not edit manually.
 * @generated
 */
final class EnvironmentTypeApi extends AbstractApi
{
    private readonly HeaderSelector $headerSelector;

    private Configuration $config;

    public function __construct(
        OAuthProvider $oauthProvider,
        ?ClientInterface $httpClient = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?Configuration $config = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
    ) {
        parent::__construct(
            $oauthProvider,
            $httpClient,
            $requestFactory,
            'https://api.platform.sh',
            $streamFactory
        );

        $this->config = $config ?? (new Configuration())->setHost('https://api.platform.sh');

        $this->headerSelector = $selector ?? new HeaderSelector();
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Get environment type links
     *
     * @throws ApiException on non-2xx response
     * @throws InvalidArgumentException|Exception
     */
    public function getEnvironmentType(
        string $projectId,
        string $environmentTypeId
    ): EnvironmentType {
        return $this->getEnvironmentTypeWithHttpInfo(
            $projectId,
            $environmentTypeId
        );
    }

    /**
     * Get environment type links
     *
     * @throws InvalidArgumentException|Exception
     */
    private function getEnvironmentTypeWithHttpInfo(
        string $projectId,
        string $environmentTypeId
    ): EnvironmentType {
        $request = $this->getEnvironmentTypeRequest(
            $projectId,
            $environmentTypeId
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                EnvironmentType::class,
                $request,
                $response
            );
        } catch (ApiException $apiException) {
            throw $apiException;
        }
    }

    /**
     * Create request for operation 'getEnvironmentType'
     *
     * @throws InvalidArgumentException
     */
    private function getEnvironmentTypeRequest(
        string $projectId,
        string $environmentTypeId
    ): RequestInterface {

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling getEnvironmentType'
            );
        }

        // verify the required parameter 'environmentTypeId' is set
        if (
            $environmentTypeId === null
            || (is_array($environmentTypeId)
            && count($environmentTypeId) === 0)
        ) {
            throw new InvalidArgumentException(
                'Missing the required parameter $environmentTypeId 
                when calling getEnvironmentType'
            );
        }

        $resourcePath = '/projects/{projectId}/environment-types/{environmentTypeId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }

        // path params
        if ($environmentTypeId !== null) {
            $resourcePath = str_replace(
                '{' . 'environmentTypeId' . '}',
                ObjectSerializer::toPathValue($environmentTypeId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Get environment types
     *
     * @throws ApiException on non-2xx response
     * @throws InvalidArgumentException|Exception
     *
     * @return EnvironmentType[]
     */
    public function listProjectsEnvironmentTypes(
        string $projectId
    ): array {
        return $this->listProjectsEnvironmentTypesWithHttpInfo(
            $projectId
        );
    }

    /**
     * Get environment types
     *
     * @throws InvalidArgumentException|Exception
     */
    private function listProjectsEnvironmentTypesWithHttpInfo(
        string $projectId
    ): array {
        $request = $this->listProjectsEnvironmentTypesRequest(
            $projectId
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\EnvironmentType[]',
                $request,
                $response
            );
        } catch (ApiException $apiException) {
            throw $apiException;
        }
    }

    /**
     * Create request for operation 'listProjectsEnvironmentTypes'
     *
     * @throws InvalidArgumentException
     */
    private function listProjectsEnvironmentTypesRequest(
        string $projectId
    ): RequestInterface {

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling listProjectsEnvironmentTypes'
            );
        }

        $resourcePath = '/projects/{projectId}/environment-types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }
}
