<?php

namespace Upsun\Api;

use Exception;
use GuzzleHttp\Psr7\MultipartStream;
use Psr\Http\Client\ClientExceptionInterface;
use Upsun\Api\Serializer\ObjectSerializer;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\StreamFactoryInterface;
use InvalidArgumentException;
use Upsun\Core\OAuthProvider;

/**
 * Low level UserAccessApi (auto-generated)
 *
 * @author    Upsun Advocacy Team
 * @license   MIT
 * @see       https://docs.upsun.com
 * @generated This file was generated by OpenAPI Generator. Do not edit manually. */
final class UserAccessApi extends AbstractApi
{
    private readonly ApiHeaderSelector $headerSelector;
    private APIConfiguration $config;

    public function __construct(
        OAuthProvider $oauthProvider,
        ?ClientInterface $httpClient = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?APIConfiguration $config = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?ApiHeaderSelector $selector = null,
    ) {
        parent::__construct(
            $oauthProvider,
            $httpClient,
            $requestFactory,
            'https://api.upsun.com',
            $streamFactory
        );

        $this->config = $config ?? (new APIConfiguration())->setHost('https://api.upsun.com');

        $this->headerSelector = $selector ?? new ApiHeaderSelector();
    }

    /**
     * Get user access for a project
     *
     * Retrieves the user's permissions for the current project.
     *
     * @return \Upsun\Model\UserProjectAccess
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/get-project-user-access
     */
    public function getProjectUserAccess(
        string $projectId,
        string $userId
    ): \Upsun\Model\UserProjectAccess {
        return $this->getProjectUserAccessWithHttpInfo(
            $projectId,
            $userId
        );
    }

    /**
     * Get user access for a project with HTTP Info
     *
     * @return \Upsun\Model\UserProjectAccess
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function getProjectUserAccessWithHttpInfo(
        string $projectId,
        string $userId
    ): \Upsun\Model\UserProjectAccess {
        $request = $this->getProjectUserAccessRequest(
            $projectId,
            $userId
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\UserProjectAccess',
                $request,
                $response
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/projects/{project_id}/user-access/{user_id}'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'getProjectUserAccess'
     *
     * @throws InvalidArgumentException
     */
    private function getProjectUserAccessRequest(
        string $projectId,
        string $userId
    ): RequestInterface {

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling getProjectUserAccess'
            );
        }

        // verify the required parameter 'userId' is set
        if (
            $userId === null
            || (is_array($userId)
            && count($userId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId 
                when calling getProjectUserAccess'
            );
        }
        $resourcePath = '/projects/{project_id}/user-access/{user_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }
        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }
    /**
     * Get project access for a user
     *
     * Retrieves the user's permissions for the current project.
     *
     * @return \Upsun\Model\UserProjectAccess
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/get-user-project-access
     */
    public function getUserProjectAccess(
        string $userId,
        string $projectId
    ): \Upsun\Model\UserProjectAccess {
        return $this->getUserProjectAccessWithHttpInfo(
            $userId,
            $projectId
        );
    }

    /**
     * Get project access for a user with HTTP Info
     *
     * @return \Upsun\Model\UserProjectAccess
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function getUserProjectAccessWithHttpInfo(
        string $userId,
        string $projectId
    ): \Upsun\Model\UserProjectAccess {
        $request = $this->getUserProjectAccessRequest(
            $userId,
            $projectId
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\UserProjectAccess',
                $request,
                $response
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/users/{user_id}/project-access/{project_id}'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'getUserProjectAccess'
     *
     * @throws InvalidArgumentException
     */
    private function getUserProjectAccessRequest(
        string $userId,
        string $projectId
    ): RequestInterface {

        // verify the required parameter 'userId' is set
        if (
            $userId === null
            || (is_array($userId)
            && count($userId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId 
                when calling getUserProjectAccess'
            );
        }

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling getUserProjectAccess'
            );
        }
        $resourcePath = '/users/{user_id}/project-access/{project_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }
        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }
    /**
     * Grant user access to a project
     *
     * Grants one or more users access to a specific project.
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/grant-project-user-access
     */
    public function grantProjectUserAccess(
        string $projectId,
        array $grantProjectUserAccessRequestInner
    ): void {
        $this->grantProjectUserAccessWithHttpInfo(
            $projectId,
            $grantProjectUserAccessRequestInner
        );
    }

    /**
     * Grant user access to a project with HTTP Info
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function grantProjectUserAccessWithHttpInfo(
        string $projectId,
        array $grantProjectUserAccessRequestInner
    ): void {
        $request = $this->grantProjectUserAccessRequest(
            $projectId,
            $grantProjectUserAccessRequestInner
        );

        try {
            $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/projects/{project_id}/user-access'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'grantProjectUserAccess'
     *
     * @throws InvalidArgumentException
     */
    private function grantProjectUserAccessRequest(
        string $projectId,
        array $grantProjectUserAccessRequestInner
    ): RequestInterface {

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling grantProjectUserAccess'
            );
        }

        // verify the required parameter 'grantProjectUserAccessRequestInner' is set
        if (
            $grantProjectUserAccessRequestInner === null
            || (is_array($grantProjectUserAccessRequestInner)
            && count($grantProjectUserAccessRequestInner) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $grantProjectUserAccessRequestInner 
                when calling grantProjectUserAccess'
            );
        }
        $resourcePath = '/projects/{project_id}/user-access';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($grantProjectUserAccessRequestInner)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(
                    ObjectSerializer::sanitizeForSerialization($grantProjectUserAccessRequestInner)
                );
            } else {
                $httpBody = $grantProjectUserAccessRequestInner;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }
    /**
     * Grant project access to a user
     *
     * Adds the user to one or more specified projects.
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/grant-user-project-access
     */
    public function grantUserProjectAccess(
        string $userId,
        array $grantUserProjectAccessRequestInner
    ): void {
        $this->grantUserProjectAccessWithHttpInfo(
            $userId,
            $grantUserProjectAccessRequestInner
        );
    }

    /**
     * Grant project access to a user with HTTP Info
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function grantUserProjectAccessWithHttpInfo(
        string $userId,
        array $grantUserProjectAccessRequestInner
    ): void {
        $request = $this->grantUserProjectAccessRequest(
            $userId,
            $grantUserProjectAccessRequestInner
        );

        try {
            $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/users/{user_id}/project-access'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'grantUserProjectAccess'
     *
     * @throws InvalidArgumentException
     */
    private function grantUserProjectAccessRequest(
        string $userId,
        array $grantUserProjectAccessRequestInner
    ): RequestInterface {

        // verify the required parameter 'userId' is set
        if (
            $userId === null
            || (is_array($userId)
            && count($userId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId 
                when calling grantUserProjectAccess'
            );
        }

        // verify the required parameter 'grantUserProjectAccessRequestInner' is set
        if (
            $grantUserProjectAccessRequestInner === null
            || (is_array($grantUserProjectAccessRequestInner)
            && count($grantUserProjectAccessRequestInner) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $grantUserProjectAccessRequestInner 
                when calling grantUserProjectAccess'
            );
        }
        $resourcePath = '/users/{user_id}/project-access';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($grantUserProjectAccessRequestInner)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(
                    ObjectSerializer::sanitizeForSerialization($grantUserProjectAccessRequestInner)
                );
            } else {
                $httpBody = $grantUserProjectAccessRequestInner;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }
    /**
     * List user access for a project
     *
     * Returns a list of items representing the project access.
     *
     * @return \Upsun\Model\ListProjectUserAccess200Response
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/list-project-user-access
     */
    public function listProjectUserAccess(
        string $projectId,
        ?int $pageSize = null,
        ?string $pageBefore = null,
        ?string $pageAfter = null,
        ?string $sort = null
    ): \Upsun\Model\ListProjectUserAccess200Response {
        return $this->listProjectUserAccessWithHttpInfo(
            $projectId,
            $pageSize,
            $pageBefore,
            $pageAfter,
            $sort
        );
    }

    /**
     * List user access for a project with HTTP Info
     *
     * @return \Upsun\Model\ListProjectUserAccess200Response
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function listProjectUserAccessWithHttpInfo(
        string $projectId,
        ?int $pageSize = null,
        ?string $pageBefore = null,
        ?string $pageAfter = null,
        ?string $sort = null
    ): \Upsun\Model\ListProjectUserAccess200Response {
        $request = $this->listProjectUserAccessRequest(
            $projectId,
            $pageSize,
            $pageBefore,
            $pageAfter,
            $sort
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\ListProjectUserAccess200Response',
                $request,
                $response
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/projects/{project_id}/user-access'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'listProjectUserAccess'
     *
     * @throws InvalidArgumentException
     */
    private function listProjectUserAccessRequest(
        string $projectId,
        ?int $pageSize = null,
        ?string $pageBefore = null,
        ?string $pageAfter = null,
        ?string $sort = null
    ): RequestInterface {

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling listProjectUserAccess'
            );
        }



        if ($pageSize !== null && $pageSize > 200) {
            throw new \InvalidArgumentException(
                'invalid value for "$pageSize" when calling UserAccessApi.listProjectUserAccess, 
                must be smaller than or equal to 200.'
            );
        }
        if ($pageSize !== null && $pageSize < 1) {
            throw new \InvalidArgumentException(
                'invalid value for "$pageSize" when calling UserAccessApi.listProjectUserAccess,
                must be bigger than or equal to 1.'
            );
        }



        $resourcePath = '/projects/{project_id}/user-access';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($pageSize !== null) {
            if ('form' === 'form' && is_array($pageSize)) {
                foreach ($pageSize as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['page[size]'] = $pageSize instanceof \DateTime
                    ? $pageSize->format(DATE_ATOM)
                    : ($pageSize);
            }
        }



        // query params
        if ($pageBefore !== null) {
            if ('form' === 'form' && is_array($pageBefore)) {
                foreach ($pageBefore as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['page[before]'] = $pageBefore instanceof \DateTime
                    ? $pageBefore->format(DATE_ATOM)
                    : ($pageBefore);
            }
        }



        // query params
        if ($pageAfter !== null) {
            if ('form' === 'form' && is_array($pageAfter)) {
                foreach ($pageAfter as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['page[after]'] = $pageAfter instanceof \DateTime
                    ? $pageAfter->format(DATE_ATOM)
                    : ($pageAfter);
            }
        }



        // query params
        if ($sort !== null) {
            if ('form' === 'form' && is_array($sort)) {
                foreach ($sort as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['sort'] = $sort instanceof \DateTime
                    ? $sort->format(DATE_ATOM)
                    : ($sort);
            }
        }



        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }
    /**
     * List project access for a user
     *
     * Returns a list of items representing the user's project access.
     *
     * @return \Upsun\Model\ListProjectUserAccess200Response
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/list-user-project-access
     */
    public function listUserProjectAccess(
        string $userId,
        ?string $filterOrganizationId = null,
        ?int $pageSize = null,
        ?string $pageBefore = null,
        ?string $pageAfter = null,
        ?string $sort = null
    ): \Upsun\Model\ListProjectUserAccess200Response {
        return $this->listUserProjectAccessWithHttpInfo(
            $userId,
            $filterOrganizationId,
            $pageSize,
            $pageBefore,
            $pageAfter,
            $sort
        );
    }

    /**
     * List project access for a user with HTTP Info
     *
     * @return \Upsun\Model\ListProjectUserAccess200Response
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function listUserProjectAccessWithHttpInfo(
        string $userId,
        ?string $filterOrganizationId = null,
        ?int $pageSize = null,
        ?string $pageBefore = null,
        ?string $pageAfter = null,
        ?string $sort = null
    ): \Upsun\Model\ListProjectUserAccess200Response {
        $request = $this->listUserProjectAccessRequest(
            $userId,
            $filterOrganizationId,
            $pageSize,
            $pageBefore,
            $pageAfter,
            $sort
        );

        try {
            $response = $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );

            return $this->handleResponseWithDataType(
                '\Upsun\Model\ListProjectUserAccess200Response',
                $request,
                $response
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/users/{user_id}/project-access'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'listUserProjectAccess'
     *
     * @throws InvalidArgumentException
     */
    private function listUserProjectAccessRequest(
        string $userId,
        ?string $filterOrganizationId = null,
        ?int $pageSize = null,
        ?string $pageBefore = null,
        ?string $pageAfter = null,
        ?string $sort = null
    ): RequestInterface {

        // verify the required parameter 'userId' is set
        if (
            $userId === null
            || (is_array($userId)
            && count($userId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId 
                when calling listUserProjectAccess'
            );
        }




        if ($pageSize !== null && $pageSize > 200) {
            throw new \InvalidArgumentException(
                'invalid value for "$pageSize" when calling UserAccessApi.listUserProjectAccess, 
                must be smaller than or equal to 200.'
            );
        }
        if ($pageSize !== null && $pageSize < 1) {
            throw new \InvalidArgumentException(
                'invalid value for "$pageSize" when calling UserAccessApi.listUserProjectAccess,
                must be bigger than or equal to 1.'
            );
        }



        $resourcePath = '/users/{user_id}/project-access';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($filterOrganizationId !== null) {
            if ('form' === 'form' && is_array($filterOrganizationId)) {
                foreach ($filterOrganizationId as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['filter[organization_id]'] = $filterOrganizationId instanceof \DateTime
                    ? $filterOrganizationId->format(DATE_ATOM)
                    : ($filterOrganizationId);
            }
        }



        // query params
        if ($pageSize !== null) {
            if ('form' === 'form' && is_array($pageSize)) {
                foreach ($pageSize as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['page[size]'] = $pageSize instanceof \DateTime
                    ? $pageSize->format(DATE_ATOM)
                    : ($pageSize);
            }
        }



        // query params
        if ($pageBefore !== null) {
            if ('form' === 'form' && is_array($pageBefore)) {
                foreach ($pageBefore as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['page[before]'] = $pageBefore instanceof \DateTime
                    ? $pageBefore->format(DATE_ATOM)
                    : ($pageBefore);
            }
        }



        // query params
        if ($pageAfter !== null) {
            if ('form' === 'form' && is_array($pageAfter)) {
                foreach ($pageAfter as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['page[after]'] = $pageAfter instanceof \DateTime
                    ? $pageAfter->format(DATE_ATOM)
                    : ($pageAfter);
            }
        }



        // query params
        if ($sort !== null) {
            if ('form' === 'form' && is_array($sort)) {
                foreach ($sort as $key => $value) {
                    $queryParams[$key] = $value;
                }
            } else {
                $queryParams['sort'] = $sort instanceof \DateTime
                    ? $sort->format(DATE_ATOM)
                    : ($sort);
            }
        }



        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }
    /**
     * Remove user access for a project
     *
     * Removes the user from the current project.
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/remove-project-user-access
     */
    public function removeProjectUserAccess(
        string $projectId,
        string $userId
    ): void {
        $this->removeProjectUserAccessWithHttpInfo(
            $projectId,
            $userId
        );
    }

    /**
     * Remove user access for a project with HTTP Info
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function removeProjectUserAccessWithHttpInfo(
        string $projectId,
        string $userId
    ): void {
        $request = $this->removeProjectUserAccessRequest(
            $projectId,
            $userId
        );

        try {
            $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/projects/{project_id}/user-access/{user_id}'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'removeProjectUserAccess'
     *
     * @throws InvalidArgumentException
     */
    private function removeProjectUserAccessRequest(
        string $projectId,
        string $userId
    ): RequestInterface {

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling removeProjectUserAccess'
            );
        }

        // verify the required parameter 'userId' is set
        if (
            $userId === null
            || (is_array($userId)
            && count($userId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId 
                when calling removeProjectUserAccess'
            );
        }
        $resourcePath = '/projects/{project_id}/user-access/{user_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }
        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('DELETE', $uri, $headers, $httpBody);
    }
    /**
     * Remove project access for a user
     *
     * Removes the user from the current project.
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/remove-user-project-access
     */
    public function removeUserProjectAccess(
        string $userId,
        string $projectId
    ): void {
        $this->removeUserProjectAccessWithHttpInfo(
            $userId,
            $projectId
        );
    }

    /**
     * Remove project access for a user with HTTP Info
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function removeUserProjectAccessWithHttpInfo(
        string $userId,
        string $projectId
    ): void {
        $request = $this->removeUserProjectAccessRequest(
            $userId,
            $projectId
        );

        try {
            $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/users/{user_id}/project-access/{project_id}'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'removeUserProjectAccess'
     *
     * @throws InvalidArgumentException
     */
    private function removeUserProjectAccessRequest(
        string $userId,
        string $projectId
    ): RequestInterface {

        // verify the required parameter 'userId' is set
        if (
            $userId === null
            || (is_array($userId)
            && count($userId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId 
                when calling removeUserProjectAccess'
            );
        }

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling removeUserProjectAccess'
            );
        }
        $resourcePath = '/users/{user_id}/project-access/{project_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }
        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('DELETE', $uri, $headers, $httpBody);
    }
    /**
     * Update user access for a project
     *
     * Updates the user's permissions for the current project.
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/update-project-user-access
     */
    public function updateProjectUserAccess(
        string $projectId,
        string $userId,
        ?\Upsun\Model\UpdateProjectUserAccessRequest $updateProjectUserAccessRequest = null
    ): void {
        $this->updateProjectUserAccessWithHttpInfo(
            $projectId,
            $userId,
            $updateProjectUserAccessRequest
        );
    }

    /**
     * Update user access for a project with HTTP Info
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function updateProjectUserAccessWithHttpInfo(
        string $projectId,
        string $userId,
        ?\Upsun\Model\UpdateProjectUserAccessRequest $updateProjectUserAccessRequest = null
    ): void {
        $request = $this->updateProjectUserAccessRequest(
            $projectId,
            $userId,
            $updateProjectUserAccessRequest
        );

        try {
            $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/projects/{project_id}/user-access/{user_id}'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'updateProjectUserAccess'
     *
     * @throws InvalidArgumentException
     */
    private function updateProjectUserAccessRequest(
        string $projectId,
        string $userId,
        ?\Upsun\Model\UpdateProjectUserAccessRequest $updateProjectUserAccessRequest = null
    ): RequestInterface {

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling updateProjectUserAccess'
            );
        }

        // verify the required parameter 'userId' is set
        if (
            $userId === null
            || (is_array($userId)
            && count($userId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId 
                when calling updateProjectUserAccess'
            );
        }

        $resourcePath = '/projects/{project_id}/user-access/{user_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }
        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($updateProjectUserAccessRequest)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(
                    ObjectSerializer::sanitizeForSerialization($updateProjectUserAccessRequest)
                );
            } else {
                $httpBody = $updateProjectUserAccessRequest;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }
    /**
     * Update project access for a user
     *
     * Updates the user's permissions for the current project.
     *
     * @throws ApiException on non-2xx response
     * @throws ClientExceptionInterface
     *
     * @see https://docs.upsun.com/api/#tag/User-Access/operation/update-user-project-access
     */
    public function updateUserProjectAccess(
        string $userId,
        string $projectId,
        ?\Upsun\Model\UpdateProjectUserAccessRequest $updateProjectUserAccessRequest = null
    ): void {
        $this->updateUserProjectAccessWithHttpInfo(
            $userId,
            $projectId,
            $updateProjectUserAccessRequest
        );
    }

    /**
     * Update project access for a user with HTTP Info
     *
     * @throws ApiException|ClientExceptionInterface
     */
    private function updateUserProjectAccessWithHttpInfo(
        string $userId,
        string $projectId,
        ?\Upsun\Model\UpdateProjectUserAccessRequest $updateProjectUserAccessRequest = null
    ): void {
        $request = $this->updateUserProjectAccessRequest(
            $userId,
            $projectId,
            $updateProjectUserAccessRequest
        );

        try {
            $this->sendAuthenticatedRequest(
                $request->getMethod(),
                (string) $request->getUri(),
                $request->getHeaders(),
                $request->getBody()
            );
        } catch (Exception $e) {
            throw new ApiException(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $e->getCode(),
                    '/users/{user_id}/project-access/{project_id}'
                ),
                $request,
                $response ?? null,
                $e
            );
        }
    }

    /**
     * Create request for operation 'updateUserProjectAccess'
     *
     * @throws InvalidArgumentException
     */
    private function updateUserProjectAccessRequest(
        string $userId,
        string $projectId,
        ?\Upsun\Model\UpdateProjectUserAccessRequest $updateProjectUserAccessRequest = null
    ): RequestInterface {

        // verify the required parameter 'userId' is set
        if (
            $userId === null
            || (is_array($userId)
            && count($userId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId 
                when calling updateUserProjectAccess'
            );
        }

        // verify the required parameter 'projectId' is set
        if (
            $projectId === null
            || (is_array($projectId)
            && count($projectId) === 0)
        ) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $projectId 
                when calling updateUserProjectAccess'
            );
        }

        $resourcePath = '/users/{user_id}/project-access/{project_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'user_id' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }
        // path params
        if ($projectId !== null) {
            $resourcePath = str_replace(
                '{' . 'project_id' . '}',
                ObjectSerializer::toPathValue($projectId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($updateProjectUserAccessRequest)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(
                    ObjectSerializer::sanitizeForSerialization($updateProjectUserAccessRequest)
                );
            } else {
                $httpBody = $updateProjectUserAccessRequest;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }
}
