generatorName: php
inputSpec: ./schema/openapispec-upsun.json
outputDir: .
packageName: upsun-client
templateDir: ./templates/php
library: psr-18
generateSupportingFiles: true
filesToSkip: ["FormDataProcessor.php"]

additionalProperties:
  invokerPackage: Upsun
  apiPackage: Api
  modelPackage: Model
  srcBasePath: src
  testsBasePath: tests
  composerVendor: upsun
  basePath: https://api.upsun.com
  docUrl: https://docs.upsun.com
  composerProject: upsun-sdk-php
  licenseName: MIT
  composerPackageName: upsun/upsun-sdk-php
  artifactUrl: https://github.com/upsun/upsun-sdk-php
  developerOrganization: Upsun Advocacy Team
  developerOrganizationUrl: https://www.upsun.com
  sdkDescription: The official Upsun SDK for PHP
  sdkLongDescription: |
    The official **Upsun SDK for PHP**. This SDK provides a PHP interface that maps to the Upsun CLI commands.

    For more information, read [the documentation](https://docs.upsun.com/api).
  escapedInvokerPackage: "Upsun\\"
  coreTestPath: ./tests/Core
  generateInterfaces: true
  projectName: Upsun SDK PHP
  authorizationUrl: https://auth.upsun.com/oauth2/token
  authorName: Upsun Advocacy Team
  basicUser: "platform-api-user"
  variableNamingConvention: "camelCase"
  parameterNamingConvention: "camelCase"
  propertyNamingConvention: "camelCase"
  enumPropertyNaming: "camelCase"
  modelPropertyNaming: "PascalCase"
  paramNaming: "camelCase"
  generateEnums: true
  enumClassPrefix: true
  sortModelPropertiesByRequiredFlag: true
  composerAuthors: |
    [
            {
                "name": "Florent HUCK",
                "email": "florent.huck@upsun.com"
            },
            {
                "name": "Mickael GAILLARD",
                "email": "mickael.gaillard@upsun.com"
            },
            {
                "name": "Upsun Advocacy Team",
                "homepage": "https://www.upsun.com"
            }
        ],
files:
  abstract_api.mustache:
    templateType: SupportingFiles
    destinationFilename: AbstractApi.php
    folder: src/Api
  oauth_provider.mustache:
    templateType: SupportingFiles
    destinationFilename: OAuthProvider.php
    folder: src/Core
  ApiObjectAttributesMapper.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiObjectAttributesMapper.php
    folder: src/Api/Serializer/
  ApiObjectFormatsMapper.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiObjectFormatsMapper.php
    folder: src/Api/Serializer/
  ApiObjectTypesMapper.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiObjectTypesMapper.php
    folder: src/Api/Serializer/
  Configuration.mustache:
    templateType: SupportingFiles
    destinationFilename: src/Api/ApiConfiguration.php
  ObjectSerializer.mustache:
    templateType: SupportingFiles
    destinationFilename: ObjectSerializer.php
    folder: src/Api/Serializer/
  ApiException.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiException.php
    folder: src/Api/
  HeaderSelector.mustache:
    templateType: SupportingFiles
    destinationFilename: ApiHeaderSelector.php
    folder: src/Api/
  ModelInterface.mustache:
    templateType: SupportingFiles
    destinationFilename: Model.php
    folder: src/Model/
  READMEDOC.mustache:
    templateType: SupportingFiles
    destinationFilename: index.md
    folder: docs/
