name: Check OpenAPI Spec Update

on:
    schedule:
        -   cron: '* 3 * * *'
    workflow_dispatch: ~
permissions:
    contents: write
env:
    DEFAULT_BRANCH: "main"
jobs:
    check-and-update:
        runs-on: ubuntu-latest
        if: ${{ github.repository_owner == 'upsun' }}

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up Git
                run: |
                    git config --global user.name "github-actions[bot]"
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"

            -   name: Install OpenAPI Generator CLI
                run: |
                    npm install -g @openapitools/openapi-generator-cli
            
            -   name: Keep existing files (removed by openapi-generator-cli generate)
                run: |
                    mv .gitignore .gitignore.bak
                    mv README.md README.md.bak
                    mv composer.json composer.json.bak
                    mv phpunit.xml.dist phpunit.xml.dist.bak
            
            -   name: Download and patch OpenAPI spec
                run: |
                    echo "Download OpenAPI spec..."
                    wget -O ./schema/openapispec-platformsh.json https://proxy.upsun.com/docs/openapispec-platformsh.json

                    echo "Patch OpenAPI spec..."
                    sed -i 's/HTTP access permissions/Http access permissions/g' ./schema/openapispec-platformsh.json

            -   name: Generate code (php)
                run: |
                    export GIT_USER_ID=upsun
                    export GIT_REPO_ID=upsun-sdk-go
                    openapi-generator-cli generate \
                      -i ./schema/openapispec-platformsh.json \
                      -g php \
                      -o apisgen \
                      --additional-properties="apiPackage=.,invokerPackage=Upsun\\Client,apiPackage=Api,modelPackage=Model,srcBasePath=src \
                      --library="psr-18"

            -   name: Remove empty phpunit tests from OpenAPI Generator 
                run: |
                    if [ -d "./test" ]; then
                        rm -Rf "./test"
                    fi
            -   name: Get back existing files (removed by openapi-generator-cli generate)
                run: |
                    mv README.md README-OPENAPI.md
                    mv README.md.bak README.md
                    mv .gitignore.bak .gitignore
                    mv composer.json.bak composer.json
                    rm -Rf phpunit.xml.dist
                    mv phpunit.xml.dist.bak phpunit.xml.dist

            -   name: Create Pull Request if changes
                uses: peter-evans/create-pull-request@v6
                with:
                    token: ${{ secrets.OPENAPI_WORKFLOW_TOKEN }}
                    commit-message: "Update OpenAPI spec"
                    body: "This PR updates the OpenAPI spec from the upstream source and applies formatting changes."

                    author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
                    signoff: false
                    draft: false
                    delete-branch: false
                    branch: update-openapi-spec
                    title: "[API-BOT] Update OpenAPI spec and regenerate SDK"

                    base: main
                    labels: |
                        report
                        automated pr
                    add-paths: |
                        schema/openapispec-platformsh.json
                        src/
                        tests/
                        docs/
                        README-OPENAPI.md
                        
                        
