name: Linting
on:
    pull_request:
        branches: [ main ]
        types: [ labeled, opened, reopened, synchronize ]
jobs:
    lint-php:
        name: Lint and Fix PHP
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.sha }}

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    tools: composer

            -   name: Install Composer dependencies
                run: composer install --prefer-dist --no-progress --no-suggest
                
            -   name: Auto-fix PHP style issues
                run: composer run fix

            -   name: Check for changes
                id: git-check
                run: |
                    if [[ -n $(git status -s) ]]; then
                      echo "changes=true" >> $GITHUB_OUTPUT
                    else
                      echo "changes=false" >> $GITHUB_OUTPUT
                    fi

            -   name: Commit and push fixes
                if: steps.git-check.outputs.changes == 'true'
                run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    git add src/Core/Tasks
                    git commit -m "Fix PHP style issues with phpcbf"
                    git push

            -   name: Run PHP lint (phpcs)
                run: composer run lint
