name: PHPUnit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: mbstring, intl, json, curl

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --testsuite "Project Test Suite"
